groundfish.track.selector<-function() {
  library(RODBC)
  channel <-  odbcConnect("PTRAN",uid = oracle.marfissci.username,pwd = oracle.marfissci.password)
#  le.DET_NAFO_UNIT_AREA_ID IN (&&AREAS) AND   
  query="SELECT 
  le.LOG_EFRT_STD_INFO_ID setid,
ps.VR_NUMBER_FISHING,
v.VESSEL_NAME,
v.GROSS_TONNAGE,
v.LOA,
ps.GEAR_CODE,
md.TRIP_ID,
le.LOG_EFRT_STD_INFO_ID,
ps.LANDED_DATE,
ps.DATE_FISHED,
le.DET_NAFO_UNIT_AREA_ID,
a.AREA,
le.ENT_LATITUDE,
le.ENT_LONGITUDE,
ROUND(SUBSTR(le.ENT_LATITUDE,1,2)+
SUBSTR(le.ENT_LATITUDE,3,2)/60+
SUBSTR(le.ENT_LATITUDE,5,2)/3600,4) lat, 
ROUND(-1*(SUBSTR(le.ENT_LONGITUDE,1,2)+
SUBSTR(le.ENT_LONGITUDE,3,2)/60+
SUBSTR(le.ENT_LONGITUDE,5,2)/3600),4) lon, 
ps.SPECIES_CODE,
s.DESC_ENG species,
ps.SPECIES_SIZE_CODE,
ps.LANDED_FORM_CODE,
le.FV_DURATION_IN_HOURS,
le.FV_NUM_OF_GEAR_UNITS,
hi.OBSERVER_FLAG,
md.TRIP_DMP_COMPANY_ID,
Sum(ps.RND_WEIGHT_KGS) RND_WEIGHT_KGS,
Sum(ps.RND_WEIGHT_KGS) val
FROM marfissci.HAIL_IN_CALLS hi, 
marfissci.LOG_EFRT_STD_INFO le,
marfissci.MON_DOCS md,
marfissci.PRO_SPC_INFO ps, 
marfissci.AREAS a,
marfissci.VESSELS v,
marfissci.SPECIES s 
WHERE s.SPECIES_CODE=ps.SPECIES_CODE AND
le.MON_DOC_ID = md.MON_DOC_ID AND
hi.HAIL_IN_CALL_ID = md.HAIL_IN_CALL_ID AND 
le.LOG_EFRT_STD_INFO_ID = ps.LOG_EFRT_STD_INFO_ID AND 
md.MON_DOC_ID = ps.MON_DOC_ID AND 
le.DET_NAFO_UNIT_AREA_ID = a.AREA_ID AND
md.VR_NUMBER = v.VR_NUMBER AND
TO_CHAR(ps.DATE_FISHED,'YYYYMMDD') Between '20160101' And '20160131' AND 
ps.SPECIES_CODE IN (130,378,371,372,377,370,376,375,369,373,374,379)
GROUP BY 
le.LOG_EFRT_STD_INFO_ID,
ps.VR_NUMBER_FISHING,
v.VESSEL_NAME,
v.GROSS_TONNAGE,
v.LOA,
ps.GEAR_CODE,
md.TRIP_ID,
le.LOG_EFRT_STD_INFO_ID,
ps.LANDED_DATE,
ps.DATE_FISHED,
le.DET_NAFO_UNIT_AREA_ID,
a.AREA,
le.ENT_LATITUDE,
le.ENT_LONGITUDE,
ROUND(SUBSTR(le.ENT_LATITUDE,1,2)+SUBSTR(le.ENT_LATITUDE,3,2)/60+SUBSTR(le.ENT_LATITUDE,5,2)/3600,4), 
ROUND(-1*(SUBSTR(le.ENT_LONGITUDE,1,2)+SUBSTR(le.ENT_LONGITUDE,3,2)/60+SUBSTR(le.ENT_LONGITUDE,5,2)/3600),4), 
ps.SPECIES_CODE,
s.DESC_ENG,
ps.SPECIES_SIZE_CODE,
ps.LANDED_FORM_CODE,
le.FV_DURATION_IN_HOURS,
le.FV_NUM_OF_GEAR_UNITS,
hi.OBSERVER_FLAG,
md.TRIP_DMP_COMPANY_ID"
  data <- sqlQuery(channel,query)
  
  results = list(data, query)
}