--------------------------------------------------------
--  DDL for Materialized View GS_CHANGE_LOG
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GS_CHANGE_LOG" ("MISSION", "SETNO", "SPEC", "FSHNO", "FSEX", "FLEN", "SDEPTH", "GEAR", "TABLE_NAME", "FIELD_NAME", "OLD_VALUE", "NEW_VALUE", "CHANGED_BY", "CHANGED_DATE", "CHANGED_WHY")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GS_CHANGE_LOG"."MISSION" "MISSION","GS_CHANGE_LOG"."SETNO" "SETNO","GS_CHANGE_LOG"."SPEC" "SPEC","GS_CHANGE_LOG"."FSHNO" "FSHNO","GS_CHANGE_LOG"."FSEX" "FSEX","GS_CHANGE_LOG"."FLEN" "FLEN","GS_CHANGE_LOG"."SDEPTH" "SDEPTH","GS_CHANGE_LOG"."GEAR" "GEAR","GS_CHANGE_LOG"."TABLE_NAME" "TABLE_NAME","GS_CHANGE_LOG"."FIELD_NAME" "FIELD_NAME","GS_CHANGE_LOG"."OLD_VALUE" "OLD_VALUE","GS_CHANGE_LOG"."NEW_VALUE" "NEW_VALUE","GS_CHANGE_LOG"."CHANGED_BY" "CHANGED_BY","GS_CHANGE_LOG"."CHANGED_DATE" "CHANGED_DATE","GS_CHANGE_LOG"."CHANGED_WHY" "CHANGED_WHY" FROM "GROUNDFISH"."GS_CHANGE_LOG"@GROUNDFISH.SABS "GS_CHANGE_LOG";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GS_CHANGE_LOG" ON "GROUNDFISH"."GS_CHANGE_LOG" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GS_CHANGE_LOG"  IS 'snapshot table for snapshot GROUNDFISH.GS_CHANGE_LOG';
  GRANT SELECT ON "GROUNDFISH"."GS_CHANGE_LOG" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GS_CHANGE_LOG" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_CHANGE_LOG" TO "GREYSONP";
