--------------------------------------------------------
--  DDL for Materialized View GS_TAXON
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GS_TAXON" ("TAXON_NAME", "AUTHORITY", "TAXON_CLASS", "TAXON_ORDER", "FAMILY", "TAXON_SYNONYMS", "COMMON_NAME", "ITIS_NUMBER", "TAXON_CODE")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GS_TAXON"."TAXON_NAME" "TAXON_NAME","GS_TAXON"."AUTHORITY" "AUTHORITY","GS_TAXON"."TAXON_CLASS" "TAXON_CLASS","GS_TAXON"."TAXON_ORDER" "TAXON_ORDER","GS_TAXON"."FAMILY" "FAMILY","GS_TAXON"."TAXON_SYNONYMS" "TAXON_SYNONYMS","GS_TAXON"."COMMON_NAME" "COMMON_NAME","GS_TAXON"."ITIS_NUMBER" "ITIS_NUMBER","GS_TAXON"."TAXON_CODE" "TAXON_CODE" FROM "GROUNDFISH"."GS_TAXON"@GROUNDFISH.SABS "GS_TAXON";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GS_TAXON" ON "GROUNDFISH"."GS_TAXON" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GS_TAXON"  IS 'snapshot table for snapshot GROUNDFISH.GS_TAXON';
  GRANT SELECT ON "GROUNDFISH"."GS_TAXON" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_TAXON" TO "GREYSONP";
