--------------------------------------------------------
--  DDL for Materialized View GSAGEMAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSAGEMAT" ("CODE", "DESCRIPTION")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSAGEMAT"."CODE" "CODE","GSAGEMAT"."DESCRIPTION" "DESCRIPTION" FROM "GROUNDFISH"."GSAGEMAT"@GROUNDFISH.SABS "GSAGEMAT";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSAGEMAT" ON "GROUNDFISH"."GSAGEMAT" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSAGEMAT"  IS 'snapshot table for snapshot GROUNDFISH.GSAGEMAT';
  GRANT SELECT ON "GROUNDFISH"."GSAGEMAT" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSAGEMAT" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAGEMAT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSAGEMAT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAGEMAT" TO "GREYSONP";
