--------------------------------------------------------
--  DDL for Materialized View GSAGER
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSAGER" ("AGER", "NAME")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS select * from groundfish.gsager@groundfish.sabs;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSAGER"  IS 'snapshot table for snapshot GROUNDFISH.GSAGER';
  GRANT SELECT ON "GROUNDFISH"."GSAGER" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSAGER" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAGER" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSAGER" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAGER" TO "GREYSONP";
