--------------------------------------------------------
--  DDL for Materialized View GSAREA2
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSAREA2" ("AREA", "UNIT", "ULLAT", "ULLONG", "LLLAT", "LLLONG", "LRLAT", "LRLONG", "URLAT", "URLONG")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS select * from groundfish.gsarea2@groundfish.sabs;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSAREA2"  IS 'snapshot table for snapshot GROUNDFISH.GSAREA2';
  GRANT SELECT ON "GROUNDFISH"."GSAREA2" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSAREA2" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAREA2" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSAREA2" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAREA2" TO "GREYSONP";
