--------------------------------------------------------
--  DDL for Materialized View GSAUX
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSAUX" ("AUX", "AUXDESC")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSAUX"."AUX" "AUX","GSAUX"."AUXDESC" "AUXDESC" FROM "GROUNDFISH"."GSAUX"@GROUNDFISH.SABS "GSAUX";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSAUX" ON "GROUNDFISH"."GSAUX" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSAUX"  IS 'snapshot table for snapshot GROUNDFISH.GSAUX';
  GRANT SELECT ON "GROUNDFISH"."GSAUX" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSAUX" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAUX" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSAUX" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSAUX" TO "GREYSONP";
