--------------------------------------------------------
--  DDL for Materialized View GSCAT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSCAT" ("MISSION", "SETNO", "SPEC", "MARKET", "SAMPWGT", "TOTWGT", "TOTNO", "CALWT", "REMARKS", "SIZE_CLASS")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSCAT"."MISSION" "MISSION","GSCAT"."SETNO" "SETNO","GSCAT"."SPEC" "SPEC","GSCAT"."MARKET" "MARKET","GSCAT"."SAMPWGT" "SAMPWGT","GSCAT"."TOTWGT" "TOTWGT","GSCAT"."TOTNO" "TOTNO","GSCAT"."CALWT" "CALWT","GSCAT"."REMARKS" "REMARKS","GSCAT"."SIZE_CLASS" "SIZE_CLASS" FROM "GROUNDFISH"."GSCAT"@GROUNDFISH.SABS "GSCAT";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSCAT" ON "GROUNDFISH"."GSCAT" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSCAT"  IS 'snapshot table for snapshot GROUNDFISH.GSCAT';
  GRANT SELECT ON "GROUNDFISH"."GSCAT" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSCAT" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSCAT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSCAT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSCAT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSCAT" TO "GREYSONP";
