--------------------------------------------------------
--  DDL for Materialized View GSDET
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSDET" ("MISSION", "SETNO", "SPEC", "FSHNO", "FLEN", "FSEX", "FMAT", "FWT", "AGMAT", "NANN", "EDGE", "CHKMRK", "AGE", "AGER", "CLEN", "REMARKS", "SIZE_CLASS")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS select * from groundfish.gsdet@groundfish.sabs;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSDET"  IS 'snapshot table for snapshot GROUNDFISH.GSDET';
  GRANT SELECT ON "GROUNDFISH"."GSDET" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSDET" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSDET" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSDET" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSDET" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSDET" TO "GREYSONP";
