--------------------------------------------------------
--  DDL for Materialized View GSEDMESS
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSEDMESS" ("MISSION", "CFLAG", "RECTYP", "SETNO", "SPEC", "FSHNO", "FSEX", "FLEN", "FLDNAM", "MESSNO", "MESS", "VAL", "OLDVAL", "NEWVAL", "COMM")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSEDMESS"."MISSION" "MISSION","GSEDMESS"."CFLAG" "CFLAG","GSEDMESS"."RECTYP" "RECTYP","GSEDMESS"."SETNO" "SETNO","GSEDMESS"."SPEC" "SPEC","GSEDMESS"."FSHNO" "FSHNO","GSEDMESS"."FSEX" "FSEX","GSEDMESS"."FLEN" "FLEN","GSEDMESS"."FLDNAM" "FLDNAM","GSEDMESS"."MESSNO" "MESSNO","GSEDMESS"."MESS" "MESS","GSEDMESS"."VAL" "VAL","GSEDMESS"."OLDVAL" "OLDVAL","GSEDMESS"."NEWVAL" "NEWVAL","GSEDMESS"."COMM" "COMM" FROM "GROUNDFISH"."GSEDMESS"@GROUNDFISH.SABS "GSEDMESS";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSEDMESS" ON "GROUNDFISH"."GSEDMESS" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSEDMESS"  IS 'snapshot table for snapshot GROUNDFISH.GSEDMESS';
  GRANT SELECT ON "GROUNDFISH"."GSEDMESS" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSEDMESS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSEDMESS" TO "GREYSONP";
