--------------------------------------------------------
--  DDL for Materialized View GSERR
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSERR" ("MESSNO", "MESS", "DESC1", "DESC2", "DESC3", "DESC4", "DESC5", "DESC6", "DESC7", "DESC8", "DESC9", "DESC10", "DESC11", "DESC12", "DESC13", "DESC14")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSERR"."MESSNO" "MESSNO","GSERR"."MESS" "MESS","GSERR"."DESC1" "DESC1","GSERR"."DESC2" "DESC2","GSERR"."DESC3" "DESC3","GSERR"."DESC4" "DESC4","GSERR"."DESC5" "DESC5","GSERR"."DESC6" "DESC6","GSERR"."DESC7" "DESC7","GSERR"."DESC8" "DESC8","GSERR"."DESC9" "DESC9","GSERR"."DESC10" "DESC10","GSERR"."DESC11" "DESC11","GSERR"."DESC12" "DESC12","GSERR"."DESC13" "DESC13","GSERR"."DESC14" "DESC14" FROM "GROUNDFISH"."GSERR"@GROUNDFISH.SABS "GSERR";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSERR" ON "GROUNDFISH"."GSERR" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSERR"  IS 'snapshot table for snapshot GROUNDFISH.GSERR';
  GRANT SELECT ON "GROUNDFISH"."GSERR" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSERR" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSERR" TO "GREYSONP";
