--------------------------------------------------------
--  DDL for Materialized View GSHOWOBT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSHOWOBT" ("HOWOBT", "HOWOBTDESC")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSHOWOBT"."HOWOBT" "HOWOBT","GSHOWOBT"."HOWOBTDESC" "HOWOBTDESC" FROM "GROUNDFISH"."GSHOWOBT"@GROUNDFISH.SABS "GSHOWOBT";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSHOWOBT" ON "GROUNDFISH"."GSHOWOBT" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSHOWOBT"  IS 'snapshot table for snapshot GROUNDFISH.GSHOWOBT';
  GRANT SELECT ON "GROUNDFISH"."GSHOWOBT" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSHOWOBT" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSHOWOBT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSHOWOBT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSHOWOBT" TO "GREYSONP";
