--------------------------------------------------------
--  DDL for Materialized View GSHYD
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSHYD" ("MISSION", "SETNO", "SDEPTH", "TEMP", "SAL", "BID", "GEAR", "EIND", "OXYML", "TAGNO")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16777216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSHYD"."MISSION" "MISSION","GSHYD"."SETNO" "SETNO","GSHYD"."SDEPTH" "SDEPTH","GSHYD"."TEMP" "TEMP","GSHYD"."SAL" "SAL","GSHYD"."BID" "BID","GSHYD"."GEAR" "GEAR","GSHYD"."EIND" "EIND","GSHYD"."OXYML" "OXYML","GSHYD"."TAGNO" "TAGNO" FROM "GROUNDFISH"."GSHYD"@GROUNDFISH.SABS "GSHYD";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSHYD" ON "GROUNDFISH"."GSHYD" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSHYD"  IS 'snapshot table for snapshot GROUNDFISH.GSHYD';
  GRANT SELECT ON "GROUNDFISH"."GSHYD" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSHYD" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSHYD" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSHYD" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSHYD" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSHYD" TO "GREYSONP";
