--------------------------------------------------------
--  DDL for Materialized View GSMATURITY
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSMATURITY" ("CODE", "DESCRIPTION")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSMATURITY"."CODE" "CODE","GSMATURITY"."DESCRIPTION" "DESCRIPTION" FROM "GROUNDFISH"."GSMATURITY"@GROUNDFISH.SABS "GSMATURITY";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSMATURITY" ON "GROUNDFISH"."GSMATURITY" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSMATURITY"  IS 'snapshot table for snapshot GROUNDFISH.GSMATURITY';
  GRANT SELECT ON "GROUNDFISH"."GSMATURITY" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSMATURITY" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSMATURITY" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSMATURITY" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSMATURITY" TO "GREYSONP";
