--------------------------------------------------------
--  DDL for Materialized View GSMISSIONS
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSMISSIONS" ("MISSION", "VESEL", "CRUNO", "YEAR", "SEASON")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSMISSIONS"."MISSION" "MISSION","GSMISSIONS"."VESEL" "VESEL","GSMISSIONS"."CRUNO" "CRUNO","GSMISSIONS"."YEAR" "YEAR","GSMISSIONS"."SEASON" "SEASON" FROM "GROUNDFISH"."GSMISSIONS"@GROUNDFISH.SABS "GSMISSIONS";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSMISSIONS" ON "GROUNDFISH"."GSMISSIONS" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSMISSIONS"  IS 'snapshot table for snapshot GROUNDFISH.GSMISSIONS';
  GRANT SELECT ON "GROUNDFISH"."GSMISSIONS" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSIONS" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSIONS" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSIONS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSIONS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSIONS" TO "GREYSONP";
