--------------------------------------------------------
--  DDL for Materialized View GSSTRATUM
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSSTRATUM" ("STRAT", "DMIN", "DMAX", "AREA", "DEPTH", "NAME")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS select * from groundfish.gsstratum@groundfish.sabs;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSSTRATUM"  IS 'snapshot table for snapshot GROUNDFISH.GSSTRATUM';
  GRANT SELECT ON "GROUNDFISH"."GSSTRATUM" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATUM" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATUM" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATUM" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATUM" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATUM" TO "GREYSONP";
