--------------------------------------------------------
--  DDL for Materialized View GSSTRATA
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSSTRATA" ("STRATA", "MAJOR", "MINOR", "LATITUDE", "LONGITUDE")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  WITH ROWID USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS SELECT "GSSTRATA"."STRATA" "STRATA","GSSTRATA"."MAJOR" "MAJOR","GSSTRATA"."MINOR" "MINOR","GSSTRATA"."LATITUDE" "LATITUDE","GSSTRATA"."LONGITUDE" "LONGITUDE" FROM "GROUNDFISH"."GSSTRATA"@GROUNDFISH.SABS "GSSTRATA";
 

  CREATE UNIQUE INDEX "GROUNDFISH"."I_SNAP$_GSSTRATA" ON "GROUNDFISH"."GSSTRATA" ("M_ROW$$") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSSTRATA"  IS 'snapshot table for snapshot GROUNDFISH.GSSTRATA';
  GRANT SELECT ON "GROUNDFISH"."GSSTRATA" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATA" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATA" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATA" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATA" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTRATA" TO "GREYSONP";
