--------------------------------------------------------
--  DDL for Materialized View GSWARPOUT
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."GSWARPOUT" ("MISSION", "SETNO", "WARPOUT")
  ORGANIZATION HEAP PCTFREE 5 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 106496 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT (trunc(sysdate+1)+19/24)
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS select * from groundfish.gswarpout@groundfish.sabs;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."GSWARPOUT"  IS 'snapshot table for snapshot GROUNDFISH.GSWARPOUT';
  GRANT SELECT ON "GROUNDFISH"."GSWARPOUT" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSWARPOUT" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSWARPOUT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSWARPOUT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSWARPOUT" TO "GREYSONP";
