--------------------------------------------------------
--  DDL for Materialized View MP_SPECIES_CODES_USED_VW
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" ("GIVEN_SPEC_CODE", "GIVEN_COMMON_NAME", "GIVEN_SCIENT_NAME", "FAO_CODE", "FAO_E_COMMON_NAME", "FAO_F_COMMON_NAME")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  PARALLEL 2 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND START WITH sysdate+0 NEXT NEXT_DAY(trunc(SysDate),'TUESDAY')+6/24
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS (
select s.code given_spec_code, s.comm given_common_name, s.spec given_scient_name,
       f.a3_code fao_code, f.english_name fao_e_common_name, f.french_name fao_f_common_name
from gsspecies s
INNER JOIN 
(select distinct sp_code from mesopelagic where sp_code is not null) c
ON s.code = c.sp_code
LEFT OUTER JOIN 
(select f2.scientific_name, a3_code, french_name, english_name
from mflib.fao_spcodes f2
INNER JOIN
  (select scientific_name, count(a3_code) cnt
  from mflib.fao_spcodes  
  group by scientific_name) f1
ON f2.scientific_name = f1.scientific_name and f1.cnt = 1
) f
on upper(f.scientific_name) in (upper(s.spec), upper(s.spec||' spp'))
WHERE s.spec is not null
);
 

  CREATE INDEX "GROUNDFISH"."MP_SPECIES_USED_PK_IDX" ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" ("GIVEN_SPEC_CODE", "GIVEN_SCIENT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 
  CREATE INDEX "GROUNDFISH"."MP_SPECIES_USED_SCIENT_IDX" ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" ("GIVEN_SCIENT_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 
  CREATE UNIQUE INDEX "GROUNDFISH"."MP_SPECIES_USED_SPEC_IDX" ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" ("GIVEN_SPEC_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."MP_SPECIES_CODES_USED_VW"  IS 'snapshot table for snapshot GROUNDFISH.MP_SPECIES_CODES_USED_VW';
  GRANT SELECT ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."MP_SPECIES_CODES_USED_VW" TO "GREYSONP";
