--------------------------------------------------------
--  DDL for Materialized View SD_ISDB_SETS_TMP
--------------------------------------------------------

  CREATE MATERIALIZED VIEW "GROUNDFISH"."SD_ISDB_SETS_TMP" ("TRIP", "GEAR_ID", "SET_NO", "NAFAREA_ID", "FISH_NO", "SEXCD_ID", "FISH_LENGTH", "FISH_WEIGHT", "SPECCD_ID", "FISHSET_ID")
  ORGANIZATION HEAP PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" 
  PARALLEL 2 
  BUILD IMMEDIATE
  USING INDEX 
  REFRESH FORCE ON DEMAND
  USING DEFAULT LOCAL ROLLBACK SEGMENT
  DISABLE QUERY REWRITE
  AS select t.trip,
       f.gear_id,
       f.set_no,
	   f.nafarea_id,
	   m.fish_no,
	   m.sexcd_id,
	   m.fish_length,
	   m.fish_weight,
	   c.speccd_id,
	   f.fishset_id
from observer.istrips t,
     observer.isfishsets f,
	 observer.isfish m,
	 observer.iscatches c
where m.catch_id = c.catch_id
  and c.fishset_id = f.fishset_id
  and f.trip_id = t.trip_id
  and t.trip IN (select distinct mission from SDDet
                 UNION
				 select distinct mission from SDSto)

;
 

  CREATE INDEX "GROUNDFISH"."SD_ISDB_TMP_FISHNO_IDX" ON "GROUNDFISH"."SD_ISDB_SETS_TMP" ("FISH_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 
  CREATE INDEX "GROUNDFISH"."SD_ISDB_TMP_SETNO_IDX" ON "GROUNDFISH"."SD_ISDB_SETS_TMP" ("SET_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 
  CREATE INDEX "GROUNDFISH"."SD_ISDB_TMP_TRIP_IDX" ON "GROUNDFISH"."SD_ISDB_SETS_TMP" ("TRIP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON MATERIALIZED VIEW "GROUNDFISH"."SD_ISDB_SETS_TMP"  IS 'snapshot table for snapshot GROUNDFISH.SD_ISDB_SETS_TMP';
  GRANT SELECT ON "GROUNDFISH"."SD_ISDB_SETS_TMP" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SD_ISDB_SETS_TMP" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SD_ISDB_SETS_TMP" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SD_ISDB_SETS_TMP" TO "GREYSONP";
