--------------------------------------------------------
--  DDL for Table ALL_SPCODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."ALL_SPCODES" 
   (	"SOURCE" VARCHAR2(4 BYTE), 
	"RESEARCH" NUMBER, 
	"SCIENTIF" VARCHAR2(50 BYTE), 
	"COMMON" VARCHAR2(50 BYTE), 
	"TSN" NUMBER, 
	"NMFS" NUMBER, 
	"IML" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."ALL_SPCODES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."ALL_SPCODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."ALL_SPCODES" TO "GREYSONP";
