--------------------------------------------------------
--  DDL for Table ASFIS_SP_FEB_2003
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."ASFIS_SP_FEB_2003" 
   (	"ISSCAAP" VARCHAR2(255 BYTE), 
	"TAXOCODE" VARCHAR2(255 BYTE), 
	"A3_CODE" VARCHAR2(255 BYTE), 
	"SCIENTIFIC_NAME" VARCHAR2(255 BYTE), 
	"ENGLISH_NAME" VARCHAR2(255 BYTE), 
	"FRENCH_NAME" VARCHAR2(255 BYTE), 
	"SPANISH_NAME" VARCHAR2(255 BYTE), 
	"AUTHOR" VARCHAR2(255 BYTE), 
	"FAMILY" VARCHAR2(255 BYTE), 
	"ORDER" VARCHAR2(255 BYTE), 
	"STATS_DATA" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_FEB_2003" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_FEB_2003" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_FEB_2003" TO "GREYSONP";
