--------------------------------------------------------
--  DDL for Table ASFIS_SP_MAR_2002
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."ASFIS_SP_MAR_2002" 
   (	"ISSCAAP" VARCHAR2(5 BYTE), 
	"TAXOCODE" VARCHAR2(15 BYTE), 
	"A3_CODE" VARCHAR2(5 BYTE), 
	"SCIENTIFIC_NAME" VARCHAR2(40 BYTE), 
	"ENGLISH_NAME" VARCHAR2(40 BYTE), 
	"FRENCH_NAME" VARCHAR2(40 BYTE), 
	"SPANISH_NAME" VARCHAR2(40 BYTE), 
	"AUTHOR" VARCHAR2(70 BYTE), 
	"FAMILY" VARCHAR2(30 BYTE), 
	"ORDER" VARCHAR2(40 BYTE), 
	"STATS_DATA" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_MAR_2002" TO "PACSHRMP";
 
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_MAR_2002" TO "ITIS";
 
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_MAR_2002" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_MAR_2002" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."ASFIS_SP_MAR_2002" TO "GREYSONP";
