--------------------------------------------------------
--  DDL for Table AVGR
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."AVGR" 
   (	"MISSION" VARCHAR2(15 BYTE), 
	"SETNO" NUMBER(3,0), 
	"SPEC" NUMBER(4,0), 
	"FLEN" NUMBER(3,0), 
	"PREY" NUMBER(4,0), 
	"AVGR" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."AVGR" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."AVGR" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."AVGR" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."AVGR" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."AVGR" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."AVGR" TO "GREYSONP";
