--------------------------------------------------------
--  DDL for Table CARD_TYPE_4
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CARD_TYPE_4" 
   (	"CARD_TYPE" CHAR(1 BYTE), 
	"VESSEL" CHAR(1 BYTE), 
	"CRUISE_NUMBER" NUMBER(2,0), 
	"SET_NUMBER" NUMBER(2,0), 
	"YEAR" NUMBER(2,0), 
	"ICNAF_DIVISION" NUMBER(2,0), 
	"DEPTH" NUMBER(3,0), 
	"BOTTOM_TEMPERATURE" NUMBER(3,0), 
	"SAMPLER" NUMBER(2,0), 
	"SPECIES" VARCHAR2(4 BYTE), 
	"RATIO" CHAR(2 BYTE), 
	"CARD_NUMBER" CHAR(1 BYTE), 
	"FISH_NUMBER" NUMBER(4,0), 
	"LENGTH_OF_FISH" NUMBER(3,0), 
	"SEX" NUMBER(1,0), 
	"MATURITY" CHAR(1 BYTE), 
	"STOMACH_CONDITION" NUMBER(1,0), 
	"VOLUME_OF_STOMACH_CONTENTS" NUMBER(5,0), 
	"NO_OF_SPECIES_IN_STOMACH" NUMBER(2,0), 
	"SPECIES_IN_STOMACH" VARCHAR2(4 BYTE), 
	"VOL_STOMACH_CONTENTS" NUMBER(5,0), 
	"AGE_MATERIAL" NUMBER(1,0), 
	"NUMBER_OF_ANNULI" NUMBER(2,0), 
	"EDGE_TYPE" NUMBER(1,0), 
	"CHECK_MARK" NUMBER(3,0), 
	"AGE" NUMBER(2,0), 
	"YEAR_CLASS" NUMBER(2,0), 
	"READ_BY" NUMBER(2,0), 
	"PARASITES" CHAR(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10649600 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
 

   COMMENT ON TABLE "GROUNDFISH"."CARD_TYPE_4"  IS 'Fish Details<br><strong><font color="RED"> **caution** these data are in original 80 character card image format, you should use tables gsinfp70, gscatp70 and gsdetp70 for analysis </font></strong>';
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_4" TO "GREYSONP";
