--------------------------------------------------------
--  DDL for Table CARD_TYPE_C
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CARD_TYPE_C" 
   (	"CARD_TYPE" VARCHAR2(1 BYTE), 
	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SETNO" NUMBER(3,0), 
	"CARD_IMAGE" VARCHAR2(107 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_C" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_C" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_C" TO "GREYSONP";
