--------------------------------------------------------
--  DDL for Table CARD_TYPE_3
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CARD_TYPE_3" 
   (	"CARD_TYPE" CHAR(1 BYTE), 
	"VESSEL" CHAR(1 BYTE), 
	"CRUISE_NUMBER" NUMBER(2,0), 
	"SET_NUMBER" NUMBER(2,0), 
	"YEAR" NUMBER(2,0), 
	"ICNAF_DIVISION" NUMBER(2,0), 
	"DEPTH" NUMBER(3,0), 
	"BOTTOM_TEMPERATURE" NUMBER(3,0), 
	"SPECIES" VARCHAR2(4 BYTE), 
	"SMLT" NUMBER(1,0), 
	"NUMBER_OF_FISH_CAUGHT" NUMBER(4,0), 
	"NUMBER_OF_BASKETS" NUMBER(4,0), 
	"RATIO" NUMBER(2,0), 
	"SEX" NUMBER(1,0), 
	"MATURITY" NUMBER(1,0), 
	"GROUPING" NUMBER(1,0), 
	"STARTING_LENGTH_GROUP" NUMBER(3,0), 
	"NUMBER_WITHIN_LENGTH_GROUP" VARCHAR2(42 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4259840 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
 

   COMMENT ON TABLE "GROUNDFISH"."CARD_TYPE_3"  IS 'Catch and Size Composition <br><strong><font color="RED"> **caution** these data are in original 80 character card image format, you should use tables gsinfp70, gscatp70 and gsdetp70 for analysis </font></strong>';
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."CARD_TYPE_3" TO "GREYSONP";
