--------------------------------------------------------
--  DDL for Table CFERRLOG
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CFERRLOG" 
   (	"ID" NUMBER(6,0), 
	"SAMPLE" VARCHAR2(15 BYTE), 
	"SOURCE" VARCHAR2(3 BYTE), 
	"SETNO" NUMBER(4,0), 
	"FISHNUMBER" NUMBER(6,0), 
	"FSRS_SAMPLED" NUMBER(4,0), 
	"MESS_ID" NUMBER(6,0), 
	"TIMESTAMP_ID" NUMBER(2,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 106496 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."ID" IS 'Error log ID';
 
   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."SAMPLE" IS 'Serial Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."SOURCE" IS 'Code for data sources';
 
   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."SETNO" IS 'Setno - 999 for no setno';
 
   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."FISHNUMBER" IS 'Unique fish number';
 
   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."FSRS_SAMPLED" IS 'Code for FSRS sampler';
 
   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."MESS_ID" IS 'Error message ID';
 
   COMMENT ON COLUMN "GROUNDFISH"."CFERRLOG"."TIMESTAMP_ID" IS 'Timestamp ID';
 
   COMMENT ON TABLE "GROUNDFISH"."CFERRLOG"  IS 'Table to store error identification information';
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "HURLEYP" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "CAPECHIDLEY" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFERRLOG" TO "GREYSONP";
