--------------------------------------------------------
--  DDL for Table CFTMPSAMPLES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CFTMPSAMPLES" 
   (	"SOURCE" VARCHAR2(3 BYTE), 
	"SAMPLE" VARCHAR2(15 BYTE), 
	"SETNO" NUMBER(5,0), 
	"FSRS_SAMPLED" VARCHAR2(3 BYTE), 
	"VESSEL_NAME" VARCHAR2(20 BYTE), 
	"CFV" VARCHAR2(8 BYTE), 
	"SPECIES" NUMBER(10,0), 
	"DATESAMPLED" DATE, 
	"DEPTH" NUMBER(5,0), 
	"FG_NORTH_LAT" NUMBER(5,0), 
	"FG_EAST_LONG" NUMBER(5,0), 
	"AREA" VARCHAR2(3 BYTE), 
	"FG_CODE" NUMBER(5,0), 
	"FISHING" VARCHAR2(1 BYTE), 
	"REMARKS" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 106496 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."CFTMPSAMPLES" TO "HURLEYP" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPSAMPLES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPSAMPLES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPSAMPLES" TO "CAPECHIDLEY" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPSAMPLES" TO "GREYSONP";
