--------------------------------------------------------
--  DDL for Table CFTMPFISH
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CFTMPFISH" 
   (	"SAMPLE" VARCHAR2(15 BYTE), 
	"SPECIES" NUMBER(5,0), 
	"FISHNUMBER" NUMBER(10,0), 
	"OTOLITHNUMBER" NUMBER(5,0), 
	"LENGTH" NUMBER(5,0), 
	"ROUNDWGT" NUMBER(5,0), 
	"GUTTEDWGT" NUMBER(5,0), 
	"LIVERWGT" NUMBER(5,0), 
	"GONADWGT" NUMBER(5,0), 
	"SEX" NUMBER(5,0), 
	"MATURITY" NUMBER(5,0), 
	"GUT_FULLNESS" NUMBER(5,0), 
	"STOMACH_NUMBER" NUMBER(5,0), 
	"COMMENTS" VARCHAR2(50 BYTE), 
	"STOMACHWGT" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 106496 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."CFTMPFISH" TO "HURLEYP" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFISH" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFISH" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFISH" TO "CAPECHIDLEY" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFISH" TO "GREYSONP";
