--------------------------------------------------------
--  DDL for Table CFTMPFSRS_SAMPLED
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CFTMPFSRS_SAMPLED" 
   (	"ID" NUMBER(10,0), 
	"TECHNICIAN" VARCHAR2(30 BYTE), 
	"TECHNICIAN_CODES" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 106496 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."CFTMPFSRS_SAMPLED" TO "HURLEYP" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFSRS_SAMPLED" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFSRS_SAMPLED" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFSRS_SAMPLED" TO "CAPECHIDLEY" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CFTMPFSRS_SAMPLED" TO "GREYSONP";
