--------------------------------------------------------
--  DDL for Table CODE_PROBS_RPT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CODE_PROBS_RPT" 
   (	"LINE_NO" NUMBER(*,0), 
	"TEXT" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."CODE_PROBS_RPT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CODE_PROBS_RPT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CODE_PROBS_RPT" TO "GREYSONP";
