--------------------------------------------------------
--  DDL for Table CODE_TYPE_LIST
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."CODE_TYPE_LIST" 
   (	"PK_CODE_TYPE" VARCHAR2(5 BYTE), 
	"CODE_DESCRIPTION" VARCHAR2(100 BYTE), 
	"COMMENTS" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."CODE_TYPE_LIST"."PK_CODE_TYPE" IS 'Standard code type';
 
   COMMENT ON COLUMN "GROUNDFISH"."CODE_TYPE_LIST"."CODE_DESCRIPTION" IS 'Description of Standard code type';
 
   COMMENT ON COLUMN "GROUNDFISH"."CODE_TYPE_LIST"."COMMENTS" IS 'Extended Description of Standard code type';
 
   COMMENT ON TABLE "GROUNDFISH"."CODE_TYPE_LIST"  IS 'Code Type List';
  GRANT SELECT ON "GROUNDFISH"."CODE_TYPE_LIST" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."CODE_TYPE_LIST" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."CODE_TYPE_LIST" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."CODE_TYPE_LIST" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."CODE_TYPE_LIST" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."CODE_TYPE_LIST" TO "GREYSONP";
