--------------------------------------------------------
--  DDL for Table DATASOURCE_LIST
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."DATASOURCE_LIST" 
   (	"FK_CODE_TYPE" VARCHAR2(5 BYTE), 
	"PK_DATASOURCE_ID" VARCHAR2(16 BYTE), 
	"DATASOURCE_DESCRIPTION" VARCHAR2(100 BYTE), 
	"COMMENTS" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."DATASOURCE_LIST"."FK_CODE_TYPE" IS 'Standard code type';
 
   COMMENT ON COLUMN "GROUNDFISH"."DATASOURCE_LIST"."PK_DATASOURCE_ID" IS 'Data Source ID code';
 
   COMMENT ON COLUMN "GROUNDFISH"."DATASOURCE_LIST"."DATASOURCE_DESCRIPTION" IS 'Description of DataSource';
 
   COMMENT ON COLUMN "GROUNDFISH"."DATASOURCE_LIST"."COMMENTS" IS 'Extended Description of DataSource';
 
   COMMENT ON TABLE "GROUNDFISH"."DATASOURCE_LIST"  IS 'Data Source List';
  GRANT SELECT ON "GROUNDFISH"."DATASOURCE_LIST" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."DATASOURCE_LIST" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."DATASOURCE_LIST" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."DATASOURCE_LIST" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."DATASOURCE_LIST" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."DATASOURCE_LIST" TO "GREYSONP";
