--------------------------------------------------------
--  DDL for Table ECNASAP_CODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."ECNASAP_CODES" 
   (	"SCIENTIFIC_NAME" VARCHAR2(50 BYTE), 
	"ENGLISH_NAME" VARCHAR2(50 BYTE), 
	"NMFS" VARCHAR2(1 BYTE), 
	"SCOTIAFUNDY" VARCHAR2(1 BYTE), 
	"SOUTHGULF" VARCHAR2(1 BYTE), 
	"NORTHGULF" VARCHAR2(1 BYTE), 
	"NFLD" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."ECNASAP_CODES" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."ECNASAP_CODES" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."ECNASAP_CODES" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."ECNASAP_CODES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."ECNASAP_CODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."ECNASAP_CODES" TO "GREYSONP";
