--------------------------------------------------------
--  DDL for Table ESPECE_GENERAL
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."ESPECE_GENERAL" 
   (	"COD_ESP_GEN" NUMBER(5,0), 
	"NOM_COMMUN_ESP_F" VARCHAR2(50 BYTE), 
	"NOM_COMMUN_ESP_A" VARCHAR2(50 BYTE), 
	"NOM_SCIENT_ESP" VARCHAR2(50 BYTE), 
	"NIVEAU_IDENT_TAXO" VARCHAR2(40 BYTE), 
	"CONTROLEE" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."ESPECE_GENERAL" TO "ITIS";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_GENERAL" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_GENERAL" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_GENERAL" TO "GREYSONP";
