--------------------------------------------------------
--  DDL for Table ESPECE_NORME_GLOBAL
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."ESPECE_NORME_GLOBAL" 
   (	"COD_NORME" NUMBER(10,0), 
	"COD_ESP_GEN" NUMBER(10,0), 
	"COD_ESPECE" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME_GLOBAL" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME_GLOBAL" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME_GLOBAL" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME_GLOBAL" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME_GLOBAL" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME_GLOBAL" TO "GREYSONP";
