--------------------------------------------------------
--  DDL for Table ESPECE_NORME
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."ESPECE_NORME" 
   (	"COD_NORME" NUMBER(5,0), 
	"COD_ESP_GEN" NUMBER(5,0), 
	"COD_ESPECE" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME" TO "ITIS";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."ESPECE_NORME" TO "GREYSONP";
