--------------------------------------------------------
--  DDL for Table GEN_SPECIES_CODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GEN_SPECIES_CODES" 
   (	"SOURCE_CD" VARCHAR2(16 BYTE), 
	"NATIVE_CD" VARCHAR2(16 BYTE), 
	"TSN" NUMBER(10,0), 
	"TSN_ORIG" NUMBER(10,0), 
	"TSN_PREF" NUMBER(10,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GEN_SPECIES_CODES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GEN_SPECIES_CODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GEN_SPECIES_CODES" TO "GREYSONP";
