--------------------------------------------------------
--  DDL for Table GRANTUTIL_MYUSERS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GRANTUTIL_MYUSERS" 
   (	"USERNAME" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GRANTUTIL_MYUSERS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GRANTUTIL_MYUSERS" TO "GREYSONP";
