--------------------------------------------------------
--  DDL for Table GS_AGEMAT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_AGEMAT" 
   (	"CODE" NUMBER(1,0), 
	"DESCRIPTION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "GALEJ";
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "NWAGSCOL" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_AGEMAT" TO "GREYSONP";
