--------------------------------------------------------
--  DDL for Table GS_ALL_STRATUM
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_ALL_STRATUM" 
   (	"FK_DATA_SOURCE" VARCHAR2(16 BYTE), 
	"STRAT" VARCHAR2(5 BYTE), 
	"MINLAT" NUMBER(8,4), 
	"MAXLAT" NUMBER(8,4), 
	"MINLONG" NUMBER(8,4), 
	"MAXLONG" NUMBER(8,4), 
	"DMIN" NUMBER(3,0), 
	"DMAX" NUMBER(3,0), 
	"DEPTH" NUMBER(3,0), 
	"AREA_NM2" NUMBER(8,2), 
	"AREA_KM2" NUMBER(8,2), 
	"NAFO" VARCHAR2(16 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_ALL_STRATUM" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_ALL_STRATUM" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_ALL_STRATUM" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_ALL_STRATUM" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_ALL_STRATUM" TO "GREYSONP";
