--------------------------------------------------------
--  DDL for Table GS_LENGTHS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_LENGTHS" 
   (	"CLASS" NUMBER, 
	"FLEN" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "SPEARST";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "BLACKJ";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "FOWLER";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "GROUNDFISH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "TRZCINSKIK";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "DENHEYER";
 
  GRANT SELECT ON "GROUNDFISH"."GS_LENGTHS" TO "GREYSONP";
