--------------------------------------------------------
--  DDL for Table GS_MGTUNITS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_MGTUNITS" 
   (	"MGTUNIT" VARCHAR2(24 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "SPEARST";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "BLACKJ";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "FOWLER";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "GROUNDFISH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_MGTUNITS" TO "GREYSONP";
