--------------------------------------------------------
--  DDL for Table GS_SURVEY_LIST
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SURVEY_LIST" 
   (	"SURVEY_ID" VARCHAR2(10 BYTE), 
	"SERIES" VARCHAR2(16 BYTE), 
	"MISSION" VARCHAR2(16 BYTE), 
	"YEAR" NUMBER(4,0), 
	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"DOCS" NUMBER(2,0), 
	"DOCNAMES" VARCHAR2(240 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "GROUNDFISH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "CHOIJ";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "MESO_GULLY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST" TO "GREYSONP";
