--------------------------------------------------------
--  DDL for Table GS_SPCODE_LOAD_PROBS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SPCODE_LOAD_PROBS" 
   (	"RESEARCH" VARCHAR2(5 BYTE), 
	"NMATCH" NUMBER, 
	"MATCHLIST" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_LOAD_PROBS" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_LOAD_PROBS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_LOAD_PROBS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_LOAD_PROBS" TO "GREYSONP";
