--------------------------------------------------------
--  DDL for Table GS_SPECIES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SPECIES" 
   (	"SPEC" NUMBER(4,0), 
	"COMM" VARCHAR2(38 BYTE), 
	"SCIEN" VARCHAR2(49 BYTE), 
	"FAO" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "SPEARST";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "BLACKJ";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "FOWLER";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "GROUNDFISH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPECIES" TO "GREYSONP";
