--------------------------------------------------------
--  DDL for Table GS_SPCODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SPCODES" 
   (	"RESEARCH" VARCHAR2(5 BYTE), 
	"LANG_ID" NUMBER(5,0), 
	"FK_MSG_ID" NUMBER(6,0), 
	"ENTR" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODES" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODES" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODES" TO "GREYSONP";
