--------------------------------------------------------
--  DDL for Table GS_STRATUM
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_STRATUM" 
   (	"STRAT" VARCHAR2(5 BYTE), 
	"AREA" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "SPEARST";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "BLACKJ";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "FOWLER";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "GROUNDFISH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_STRATUM" TO "GREYSONP";
