--------------------------------------------------------
--  DDL for Table GS_SPCODE_TYPES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SPCODE_TYPES" 
   (	"SPCODE_TYPE" VARCHAR2(10 BYTE), 
	"SPCODE_TYPE_DESC" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_TYPES" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_TYPES" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_TYPES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_TYPES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_TYPES" TO "GREYSONP";
