--------------------------------------------------------
--  DDL for Table GS_SURVEY_LIST_OLD
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SURVEY_LIST_OLD" 
   (	"SURVEY_ID" VARCHAR2(10 BYTE), 
	"SERIES" VARCHAR2(8 BYTE), 
	"YEAR" NUMBER, 
	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"DOCS" NUMBER, 
	"DOCNAMES" VARCHAR2(240 BYTE), 
	"MISSION" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST_OLD" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST_OLD" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SURVEY_LIST_OLD" TO "GREYSONP";
