--------------------------------------------------------
--  DDL for Table GS_SPCODE_XREF
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SPCODE_XREF" 
   (	"RESEARCH" VARCHAR2(5 BYTE), 
	"SPCODE_TYPE" VARCHAR2(10 BYTE), 
	"SPCODE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_XREF" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_XREF" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_XREF" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_XREF" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SPCODE_XREF" TO "GREYSONP";
