--------------------------------------------------------
--  DDL for Table GS_SERIES_STRAT_LIST
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GS_SERIES_STRAT_LIST" 
   (	"SERIES" VARCHAR2(8 BYTE), 
	"STRAT" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "SPEARST";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "BLACKJ";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "FOWLER";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "GROUNDFISH";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GS_SERIES_STRAT_LIST" TO "GREYSONP";
