--------------------------------------------------------
--  DDL for Table GSCATP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSCATP70" 
   (	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SETNO" NUMBER(3,0), 
	"SPEC" NUMBER(4,0), 
	"TOTNO" NUMBER(6,0), 
	"TOTWGT" NUMBER(12,3), 
	"SAMPWGT" NUMBER(12,3), 
	"CALWT" NUMBER(1,0), 
	"SAMPNO" NUMBER(6,0), 
	"ESTSAMPMULT" NUMBER(8,4), 
	"BASKNO" NUMBER(5,1), 
	"BASKWT" NUMBER(6,1), 
	"SIZE_CLASS" NUMBER(1,0), 
	"MISSION" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2129920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."VESEL" IS 'Vessel code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."CRUNO" IS 'Cruise Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."SPEC" IS 'Species Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."TOTNO" IS 'True Total Number Caught';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."TOTWGT" IS 'Estimated Total Weight Caught';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."SAMPWGT" IS 'Estimated Sample Weight';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."CALWT" IS 'Weight Calculation method code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."SAMPNO" IS 'Estimated Number in sample';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."ESTSAMPMULT" IS 'Calculated Sample Multiplier';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."BASKNO" IS 'True Number of Baskets Caught';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."BASKWT" IS 'Calculated Weight of Baskets Caught';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCATP70"."SIZE_CLASS" IS 'Size Class';
 
   COMMENT ON TABLE "GROUNDFISH"."GSCATP70"  IS 'Catch data for species P70- working temp table';
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "BRANTON";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSCATP70" TO "GREYSONP";
