--------------------------------------------------------
--  DDL for Table GSCRUP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSCRUP70" 
   (	"SERIESID" NUMBER, 
	"CR_YEAR" NUMBER(4,0), 
	"ICNAF" VARCHAR2(15 BYTE), 
	"CRUISE_LIST" VARCHAR2(25 BYTE), 
	"VESEL" CHAR(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"CR_DATES" VARCHAR2(25 BYTE), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"SETSTNS" VARCHAR2(10 BYTE), 
	"SETS" NUMBER, 
	"STATIONS" NUMBER, 
	"PURPOSE" VARCHAR2(100 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."SERIESID" IS 'series Id code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."CR_YEAR" IS 'year of cruise';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."ICNAF" IS 'ICNAF area';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."CRUISE_LIST" IS 'Cruise(s) Identification';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."VESEL" IS 'Vessel code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."CRUNO" IS 'Cruise Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."CR_DATES" IS 'Cruise Dates';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."SDATE" IS 'Start Date';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."EDATE" IS 'End Date';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSCRUP70"."SETSTNS" IS 'Sets(and stations)';
 
   COMMENT ON TABLE "GROUNDFISH"."GSCRUP70"  IS 'Cruise Description';
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "TRZCINSKIK";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "DENHEYER";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUP70" TO "GREYSONP";
