--------------------------------------------------------
--  DDL for Table GSCRUISELIST
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSCRUISELIST" 
   (	"YEAR" NUMBER(4,0), 
	"NAFO" VARCHAR2(7 BYTE), 
	"VESL" VARCHAR2(3 BYTE), 
	"CRUNO" NUMBER(22,0), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"SETS" VARCHAR2(7 BYTE), 
	"PURPOSE" VARCHAR2(80 BYTE), 
	"LOCALE" VARCHAR2(80 BYTE), 
	"DATASOURCE" VARCHAR2(12 BYTE), 
	"DATASTATUS" VARCHAR2(8 BYTE), 
	"DATALOCATION" VARCHAR2(12 BYTE), 
	"MISSION" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "GALEJ";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "NWAGSCOL" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "TRZCINSKIK";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "DENHEYER";
 
  GRANT SELECT ON "GROUNDFISH"."GSCRUISELIST" TO "GREYSONP";
