--------------------------------------------------------
--  DDL for Table GSDETP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSDETP70" 
   (	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SETNO" NUMBER(3,0), 
	"SPEC" NUMBER(4,0), 
	"FSHNO" NUMBER(4,0), 
	"FLEN" NUMBER(3,0), 
	"FSEX" NUMBER(1,0), 
	"FMAT" NUMBER(1,0), 
	"AGMAT" NUMBER(1,0), 
	"NANN" NUMBER(2,0), 
	"EDGE" NUMBER(1,0), 
	"CHKMRK" VARCHAR2(3 BYTE), 
	"AGE" NUMBER(2,0), 
	"AGER" VARCHAR2(2 BYTE), 
	"CLEN" NUMBER(4,0), 
	"SIZE_CLASS" NUMBER(1,0), 
	"MISSION" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 11550720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."VESEL" IS 'Vessel code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."CRUNO" IS 'Cruise Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."SPEC" IS 'Species';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."FSHNO" IS 'Fish Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."FLEN" IS 'length';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."FSEX" IS 'sex';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."FMAT" IS 'maturity';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."AGMAT" IS 'aging material';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."NANN" IS 'Number of annuli';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."EDGE" IS 'Edge type';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."CHKMRK" IS 'Check Mark';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."AGE" IS 'Age';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."AGER" IS 'Ager';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."CLEN" IS 'Count at length';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSDETP70"."SIZE_CLASS" IS 'size class';
 
   COMMENT ON TABLE "GROUNDFISH"."GSDETP70"  IS 'Detailed Catch data by species P70- working temp table';
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "BRANTON";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "TRZCINSKIK";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "DENHEYER";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSDETP70" TO "GREYSONP";
