--------------------------------------------------------
--  DDL for Table GSDINF_TYPE1
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSDINF_TYPE1" 
   (	"SERIES" VARCHAR2(16 BYTE), 
	"YEAR" NUMBER, 
	"MISSION" VARCHAR2(10 BYTE), 
	"SETNO" NUMBER(3,0), 
	"PRI_SET_NO" NUMBER, 
	"SDATE" DATE, 
	"STRAT" VARCHAR2(3 BYTE), 
	"SLAT" NUMBER, 
	"SLONG" NUMBER, 
	"DEPTH" NUMBER, 
	"GEAR" NUMBER(2,0), 
	"DIST" NUMBER(6,2), 
	"XTYPE" NUMBER(1,0), 
	"STEMP" NUMBER, 
	"SSAL" NUMBER, 
	"BTEMP" NUMBER, 
	"BSAL" NUMBER
   ) PCTFREE 0 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSDINF_TYPE1" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSDINF_TYPE1" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSDINF_TYPE1" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSDINF_TYPE1" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSDINF_TYPE1" TO "GREYSONP";
