--------------------------------------------------------
--  DDL for Table GSINFP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSINFP70" 
   (	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SETNO" NUMBER(3,0), 
	"STATION" NUMBER(3,0), 
	"SDATE" DATE, 
	"TIME" NUMBER(4,0), 
	"SLAT" NUMBER(8,2), 
	"SLONG" NUMBER(8,2), 
	"ELAT" NUMBER(8,2), 
	"ELONG" NUMBER(8,2), 
	"AREA" VARCHAR2(3 BYTE), 
	"DUR" NUMBER(3,0), 
	"DIST" NUMBER(6,2), 
	"HOWD" NUMBER(1,0), 
	"SPEED" NUMBER(6,2), 
	"HOWS" NUMBER(1,0), 
	"DMIN" NUMBER(3,0), 
	"DMAX" NUMBER(3,0), 
	"WIND" NUMBER(3,0), 
	"FORCE" NUMBER(1,0), 
	"CURNT" NUMBER(1,0), 
	"TYPE" NUMBER(1,0), 
	"GEAR" NUMBER(2,0), 
	"AUX" NUMBER(1,0), 
	"DEPTH" NUMBER(3,0), 
	"ETIME" DATE, 
	"REMARKS" VARCHAR2(256 BYTE), 
	"BOTTOM_TEMPERATURE" NUMBER(4,1), 
	"MISSION" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 532480 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."VESEL" IS 'Vessel code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."CRUNO" IS 'Cruise Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."STATION" IS 'Station ID';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."SDATE" IS 'Start Date';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."TIME" IS 'Start Time';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."SLAT" IS 'Start Latitude';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."SLONG" IS 'Start Longitude';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."ELAT" IS 'End Latitude';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."ELONG" IS 'End Longitude';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."AREA" IS 'Area';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."DUR" IS 'Duration ';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."DIST" IS 'Distance towed';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."HOWD" IS 'How distance obtained';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."SPEED" IS 'Speed';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."HOWS" IS 'How Speed obtained';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."DMIN" IS 'Minimum depth';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."DMAX" IS 'Maximum depth';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."WIND" IS 'Wind';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."FORCE" IS 'Force';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."CURNT" IS 'Current';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."TYPE" IS 'Experiment type';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."GEAR" IS 'Gear';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."AUX" IS 'Auxiliary gear';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."DEPTH" IS 'Depth';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."ETIME" IS 'End time';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."REMARKS" IS 'remarks';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSINFP70"."BOTTOM_TEMPERATURE" IS 'Bottom temperature';
 
   COMMENT ON TABLE "GROUNDFISH"."GSINFP70"  IS 'Set Position and specifics P70';
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "BRANTON";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "TRZCINSKIK";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "DENHEYER";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSINFP70" TO "GREYSONP";
