--------------------------------------------------------
--  DDL for Table GSLOADP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSLOADP70" 
   (	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SETNO" NUMBER(3,0), 
	"SPECIES" VARCHAR2(4 BYTE), 
	"RATIO_CORR" VARCHAR2(1 BYTE), 
	"CORR1" VARCHAR2(1 BYTE), 
	"CORR2" VARCHAR2(1 BYTE), 
	"CORR3" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSLOADP70" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSLOADP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSLOADP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSLOADP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSLOADP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSLOADP70" TO "GREYSONP";
