--------------------------------------------------------
--  DDL for Table GSMGT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSMGT" 
   (	"UNIT" VARCHAR2(20 BYTE), 
	"STRAT" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "SPEARST";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "BLACKJ";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "FOWLER";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "GROUNDFISH";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "KOELLERP";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "PCOMEAU";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "CHOIJ";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "NWAGSCOL" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "PED_HALIBUT";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "TRZCINSKIK";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "LUSSEAUS";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "MESO_GULLY";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "DENHEYER";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSMGT" TO "GREYSONP";
