--------------------------------------------------------
--  DDL for Table GSMISSION_LIST_2010MAR14
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSMISSION_LIST_2010MAR14" 
   (	"PK_MISSION" VARCHAR2(16 BYTE), 
	"FK_SERIES_ID" VARCHAR2(16 BYTE), 
	"YEAR" NUMBER(4,0), 
	"VESEL" VARCHAR2(3 BYTE), 
	"CRUNO" NUMBER(4,0), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"SETS" VARCHAR2(7 BYTE), 
	"PURPOSE" VARCHAR2(80 BYTE), 
	"LOCALE" VARCHAR2(80 BYTE), 
	"DATASOURCE" VARCHAR2(80 BYTE), 
	"DATASTATUS" VARCHAR2(80 BYTE), 
	"DATALOCATION" VARCHAR2(80 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "KOELLERP";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "PCOMEAU";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "FRAILC";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "CHOIJ";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "SAMEOTOJ";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSMISSION_LIST_2010MAR14" TO "GREYSONP";
