--------------------------------------------------------
--  DDL for Table GSRATIO
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSRATIO" 
   (	"CRUISEID" VARCHAR2(10 BYTE), 
	"SPECIES" VARCHAR2(4 BYTE), 
	"RATIO" NUMBER, 
	"FLAG9" VARCHAR2(1 BYTE), 
	"RATIOERROR" VARCHAR2(1 BYTE), 
	"MFC" NUMBER(3,0), 
	"MINCLEN" NUMBER(3,0), 
	"MAXCLEN" NUMBER(3,0), 
	"MULTIPLIER" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."CRUISEID" IS 'Cruise Id vessel-No-Set';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."SPECIES" IS 'Species Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."RATIO" IS 'coded ratio';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."FLAG9" IS 'count = 999 flag ie overflow records';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."RATIOERROR" IS 'ratio error flag';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."MFC" IS 'number of frequency counts';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."MINCLEN" IS 'minimum count at length';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."MAXCLEN" IS 'maximum count at length';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSRATIO"."MULTIPLIER" IS 'estimated sampling multiplier';
 
   COMMENT ON TABLE "GROUNDFISH"."GSRATIO"  IS 'Sampling Ratio problems warning table';
  GRANT SELECT ON "GROUNDFISH"."GSRATIO" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSRATIO" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSRATIO" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSRATIO" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSRATIO" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSRATIO" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSRATIO" TO "GREYSONP";
