--------------------------------------------------------
--  DDL for Table GSS3LF_XXX
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSS3LF_XXX" 
   (	"SERIES" VARCHAR2(16 BYTE), 
	"YEAR" NUMBER, 
	"STRAT" VARCHAR2(3 BYTE), 
	"NTOWS" NUMBER, 
	"SPEC" NUMBER(4,0), 
	"FSEX" NUMBER, 
	"FLEN" NUMBER, 
	"AVGCLEN" NUMBER, 
	"VARCLEN" NUMBER, 
	"AVGSTDCLEN" NUMBER, 
	"VARSTDCLEN" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "GROUNDFISH"."GSS3LF_XXX" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSS3LF_XXX" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSS3LF_XXX" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSS3LF_XXX" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSS3LF_XXX" TO "GREYSONP";
