--------------------------------------------------------
--  DDL for Table GSSALK_VS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSSALK_VS" 
   (	"T" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSSALK_VS" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSALK_VS" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSALK_VS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSALK_VS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSALK_VS" TO "GREYSONP";
