--------------------------------------------------------
--  DDL for Table GSSAMPRATIO
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSSAMPRATIO" 
   (	"CRUSETSPID" VARCHAR2(14 BYTE), 
	"SAMPMULT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSSAMPRATIO"."CRUSETSPID" IS 'vessel-cruise-Set-species ID';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSAMPRATIO"."SAMPMULT" IS 'Sample No * sampMult = TotalNo';
 
   COMMENT ON TABLE "GROUNDFISH"."GSSAMPRATIO"  IS 'Sample Multipliers for all vessel-cruise-Set-species';
  GRANT SELECT ON "GROUNDFISH"."GSSAMPRATIO" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSSAMPRATIO" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSAMPRATIO" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSSAMPRATIO" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSSAMPRATIO" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSAMPRATIO" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSAMPRATIO" TO "GREYSONP";
