--------------------------------------------------------
--  DDL for Table GSSPGRPDESP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSSPGRPDESP70" 
   (	"GRPID" NUMBER(4,0), 
	"DESCRIPTION" VARCHAR2(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSSPGRPDESP70"."GRPID" IS 'Species Group Id';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSPGRPDESP70"."DESCRIPTION" IS 'Species Group Description';
 
   COMMENT ON TABLE "GROUNDFISH"."GSSPGRPDESP70"  IS 'Species Group Description';
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPDESP70" TO "GREYSONP";
