--------------------------------------------------------
--  DDL for Table GSSPGRPP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSSPGRPP70" 
   (	"SPEC" NUMBER(4,0), 
	"GRPID" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSSPGRPP70"."SPEC" IS 'Species Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSPGRPP70"."GRPID" IS 'Species Group Id';
 
   COMMENT ON TABLE "GROUNDFISH"."GSSPGRPP70"  IS 'Species Group Coding';
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPGRPP70" TO "GREYSONP";
