--------------------------------------------------------
--  DDL for Table GSSPECIESEDIT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSSPECIESEDIT" 
   (	"SPEC" VARCHAR2(49 BYTE), 
	"COMM" VARCHAR2(38 BYTE), 
	"CODE" NUMBER(4,0), 
	"NMFS" NUMBER(4,0), 
	"ENTR" DATE, 
	"AUTHORITY" VARCHAR2(100 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"TSN" NUMBER(38,0), 
	"EDITED_NAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSSPECIESEDIT" TO PUBLIC;
 
  GRANT ALTER ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT DELETE ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT INDEX ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT INSERT ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT UPDATE ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT REFERENCES ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT ON COMMIT REFRESH ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT QUERY REWRITE ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT DEBUG ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT FLASHBACK ON "GROUNDFISH"."GSSPECIESEDIT" TO "MARY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECIESEDIT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECIESEDIT" TO "GREYSONP";
