--------------------------------------------------------
--  DDL for Table GSSPECP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSSPECP70" 
   (	"SPEC" NUMBER(4,0), 
	"LWA" NUMBER(6,4), 
	"LWB" NUMBER(6,2), 
	"SEXED" VARCHAR2(1 BYTE), 
	"GROUPING" NUMBER(1,0), 
	"BSKWGT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSSPECP70"."SPEC" IS 'Species Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSPECP70"."LWA" IS 'length weight coef. a';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSPECP70"."LWB" IS 'length weight coef. b';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSPECP70"."SEXED" IS 'Sexed lf count indicator';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSPECP70"."GROUPING" IS 'Standard grouping';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSPECP70"."BSKWGT" IS 'Basket weight';
 
   COMMENT ON TABLE "GROUNDFISH"."GSSPECP70"  IS 'Species conversion data P70';
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "OBSERVER";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSPECP70" TO "GREYSONP";
