--------------------------------------------------------
--  DDL for Table GSSTOP70
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSSTOP70" 
   (	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"SETNO" NUMBER(3,0), 
	"SPEC" NUMBER(4,0), 
	"FSHNO" NUMBER(4,0), 
	"STOSPEC" VARCHAR2(4 BYTE), 
	"PARTVOL" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 532480 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."GSSTOP70"."VESEL" IS 'Vessel code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSTOP70"."CRUNO" IS 'Cruise Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSTOP70"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSTOP70"."SPEC" IS 'Species Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSTOP70"."FSHNO" IS 'Fish number';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSTOP70"."STOSPEC" IS 'Species code in stomach';
 
   COMMENT ON COLUMN "GROUNDFISH"."GSSTOP70"."PARTVOL" IS 'Volume in stomach';
 
   COMMENT ON TABLE "GROUNDFISH"."GSSTOP70"  IS 'Stomach content data P70';
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "JSIMON";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "COOKA";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSSTOP70" TO "GREYSONP";
