--------------------------------------------------------
--  DDL for Table GSVESSEL
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSVESSEL" 
   (	"VESEL" VARCHAR2(1 BYTE), 
	"VNAME" VARCHAR2(15 BYTE), 
	"BDATE" DATE, 
	"EDATE" DATE, 
	"GEAR1" NUMBER(2,0), 
	"GEAR2" NUMBER(2,0), 
	"GEAR3" NUMBER(2,0), 
	"GEAR4" NUMBER(2,0), 
	"GEAR5" NUMBER(2,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO PUBLIC;
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "GALEJ";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "NWAGSCOL" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "TRZCINSKIK";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "DENHEYER";
 
  GRANT SELECT ON "GROUNDFISH"."GSVESSEL" TO "GREYSONP";
