--------------------------------------------------------
--  DDL for Table GSXTYPE_BRIEF
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."GSXTYPE_BRIEF" 
   (	"XTYPE" NUMBER(1,0), 
	"XTYPEDESC" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."GSXTYPE_BRIEF" TO "GREYSONP";
