--------------------------------------------------------
--  DDL for Table HERRINGDET_TMP
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."HERRINGDET_TMP" 
   (	"MISSION" VARCHAR2(10 BYTE), 
	"SPEC" NUMBER(4,0), 
	"SETNO" NUMBER(4,0), 
	"FSHNO" NUMBER(4,0), 
	"FLEN" NUMBER(4,0), 
	"FWT" NUMBER(4,0), 
	"MORPH1" NUMBER(4,0), 
	"GUTFULLNESS" NUMBER(4,0), 
	"MORPHCD" NUMBER(4,0), 
	"STOMACH_NO" NUMBER(4,0), 
	"REMARKS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 532480 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."MISSION" IS 'trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."SPEC" IS 'species';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."SETNO" IS 'setno number ';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."FSHNO" IS 'fish number';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."FLEN" IS 'fish length';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."FWT" IS 'fish weight ';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."MORPH1" IS 'morpology values';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."GUTFULLNESS" IS 'gut condition code ';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."MORPHCD" IS 'morpology code';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."STOMACH_NO" IS 'maturity code';
 
   COMMENT ON COLUMN "GROUNDFISH"."HERRINGDET_TMP"."REMARKS" IS 'remarks';
 
   COMMENT ON TABLE "GROUNDFISH"."HERRINGDET_TMP"  IS 'Herring Detail temp ';
  GRANT SELECT ON "GROUNDFISH"."HERRINGDET_TMP" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."HERRINGDET_TMP" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."HERRINGDET_TMP" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."HERRINGDET_TMP" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."HERRINGDET_TMP" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."HERRINGDET_TMP" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."HERRINGDET_TMP" TO "GREYSONP";
