--------------------------------------------------------
--  DDL for Table JOIN_SPCODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."JOIN_SPCODES" 
   (	"RESEARCH" NUMBER(4,0), 
	"ICNAF" VARCHAR2(3 BYTE), 
	"FAO" VARCHAR2(3 BYTE), 
	"COMMON" VARCHAR2(38 BYTE), 
	"SCIENTIF" VARCHAR2(49 BYTE), 
	"COMMER" VARCHAR2(3 BYTE), 
	"NMFS" NUMBER, 
	"ENTR" NUMBER, 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"IML" NUMBER(5,0), 
	"ENGLISHCOMMONNAME" VARCHAR2(50 BYTE), 
	"FRENCHCOMMONNAME" VARCHAR2(50 BYTE), 
	"SCIENTIFICNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."JOIN_SPCODES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."JOIN_SPCODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."JOIN_SPCODES" TO "GREYSONP";
