--------------------------------------------------------
--  DDL for Table LFREPORT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."LFREPORT" 
   (	"RPTROWNUM" NUMBER, 
	"TITLE1" CHAR(15 BYTE), 
	"COLG3" CHAR(55 BYTE), 
	"TITLE2" CHAR(7 BYTE), 
	"COLG2" CHAR(19 BYTE), 
	"TITLE3" CHAR(7 BYTE), 
	"COLG1" CHAR(157 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "BONDS";
 
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "MFD_OBFMI";
 
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."LFREPORT" TO "GREYSONP";
