--------------------------------------------------------
--  DDL for Table MESOPELAGIC_GEAR_CODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."MESOPELAGIC_GEAR_CODES" 
   (	"GEARCD_ID" NUMBER(4,0), 
	"DESCRIPTION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC_GEAR_CODES" TO "BAJONAL";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC_GEAR_CODES" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC_GEAR_CODES" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC_GEAR_CODES" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC_GEAR_CODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC_GEAR_CODES" TO "GREYSONP";
