--------------------------------------------------------
--  DDL for Table MESOPELAGIC
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."MESOPELAGIC" 
   (	"CRUISE" VARCHAR2(6 BYTE), 
	"STATION" NUMBER, 
	"DAY" NUMBER, 
	"MONTH" NUMBER, 
	"YEAR" NUMBER, 
	"SALINITY" NUMBER, 
	"WAT_MAS" NUMBER, 
	"CTD_NO" NUMBER, 
	"XBT_NO" NUMBER, 
	"BC_NO" NUMBER, 
	"HY_GEAR" NUMBER, 
	"SUR_TEMP" NUMBER, 
	"LAT_DEG" NUMBER, 
	"LAT_MIN" NUMBER, 
	"LON_DEG" NUMBER, 
	"LON_MIN" NUMBER, 
	"SKY_COND" VARCHAR2(8 BYTE), 
	"AIR_TEMP" NUMBER, 
	"AIR_PRES" NUMBER, 
	"WIND_SPD" NUMBER, 
	"CLOUD_TP" NUMBER, 
	"CLOUD_CV" NUMBER, 
	"SAMP_NO" NUMBER, 
	"GEAR" NUMBER, 
	"TOW_TYPE" NUMBER, 
	"TDETAILS" NUMBER, 
	"START_MN" NUMBER, 
	"START_HR" NUMBER, 
	"SHIP_SPD" NUMBER, 
	"SHIP_HD" NUMBER, 
	"DEPTHTOW" NUMBER, 
	"DEPTHGET" NUMBER, 
	"TOW_TIME" NUMBER, 
	"HAULTIME" NUMBER, 
	"DEPTHBOT" NUMBER, 
	"VOL_TOT" NUMBER, 
	"VOL_FISH" NUMBER, 
	"VOL_JEL" NUMBER, 
	"VOL_OTH" NUMBER, 
	"SHELF_WT" NUMBER, 
	"NUM_SPEC" NUMBER, 
	"TOW_CL" NUMBER, 
	"TOT_COT" NUMBER, 
	"MIN_SIZE" NUMBER, 
	"MAX_SIZE" NUMBER, 
	"SP_STAGE" VARCHAR2(8 BYTE), 
	"SP_CODE" NUMBER, 
	"FAMILY" NUMBER, 
	"SORTER" VARCHAR2(6 BYTE), 
	"LAB_ID" VARCHAR2(6 BYTE), 
	"LAB_NUM" NUMBER, 
	"SINKTIME" NUMBER, 
	"COLX" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC" TO "BAJONAL";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."MESOPELAGIC" TO "GREYSONP";
