--------------------------------------------------------
--  DDL for Table MWDATA_LOCATION
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."MWDATA_LOCATION" 
   (	"PK_SOURCE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(80 BYTE), 
	"LINKAGE_NOTES" VARCHAR2(1000 BYTE), 
	"LINK_URL" VARCHAR2(255 BYTE), 
	"DATABASE_LINK_INFO" VARCHAR2(255 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"SITE_ACTIVE" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."MWDATA_LOCATION" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."MWDATA_LOCATION" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."MWDATA_LOCATION" TO "GREYSONP";
