--------------------------------------------------------
--  DDL for Table MWMISSION_LIST
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."MWMISSION_LIST" 
   (	"PK_MISSION" VARCHAR2(16 BYTE), 
	"FK_SERIES_ID" VARCHAR2(16 BYTE), 
	"YEAR" NUMBER(4,0), 
	"VESEL" VARCHAR2(3 BYTE), 
	"CRUNO" NUMBER(4,0), 
	"SDATE" DATE, 
	"EDATE" DATE, 
	"SETS" VARCHAR2(7 BYTE), 
	"PURPOSE" VARCHAR2(80 BYTE), 
	"LOCALE" VARCHAR2(80 BYTE), 
	"DATASOURCE" VARCHAR2(80 BYTE), 
	"DATASTATUS" VARCHAR2(80 BYTE), 
	"DATALOCATION" VARCHAR2(80 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."MWMISSION_LIST" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."MWMISSION_LIST" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."MWMISSION_LIST" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."MWMISSION_LIST" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."MWMISSION_LIST" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."MWMISSION_LIST" TO "GREYSONP";
