--------------------------------------------------------
--  DDL for Table NFGSINF
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."NFGSINF" 
   (	"SERIES" CHAR(4 BYTE), 
	"YEAR" NUMBER, 
	"MISSION" VARCHAR2(10 BYTE), 
	"SETNO" NUMBER, 
	"PRI_SET_NO" NUMBER, 
	"SDATE" DATE, 
	"STRAT" VARCHAR2(3 BYTE), 
	"SLAT" NUMBER, 
	"SLONG" NUMBER, 
	"DEPTH" NUMBER, 
	"GEAR" VARCHAR2(4 BYTE), 
	"DIST" VARCHAR2(3 BYTE), 
	"XTYPE" VARCHAR2(2 BYTE), 
	"STEMP" VARCHAR2(3 BYTE), 
	"SSAL" NUMBER, 
	"BTEMP" VARCHAR2(3 BYTE), 
	"BSAL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON TABLE "GROUNDFISH"."NFGSINF"  IS 'tow time, location, depth, etc ...';
  GRANT SELECT ON "GROUNDFISH"."NFGSINF" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSINF" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSINF" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSINF" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSINF" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSINF" TO "GREYSONP";
