--------------------------------------------------------
--  DDL for Table NFGSCAT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."NFGSCAT" 
   (	"SERIES" CHAR(4 BYTE), 
	"YEAR" NUMBER, 
	"MISSION" VARCHAR2(10 BYTE), 
	"SETNO" NUMBER, 
	"PRI_SET_NO" NUMBER, 
	"SDATE" DATE, 
	"STRAT" VARCHAR2(3 BYTE), 
	"SPEC" VARCHAR2(4 BYTE), 
	"SPECX" CHAR(4 BYTE), 
	"TOTWGT" VARCHAR2(7 BYTE), 
	"TOTNO" VARCHAR2(6 BYTE), 
	"STDWGT" NUMBER, 
	"STDNO" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
 

   COMMENT ON TABLE "GROUNDFISH"."NFGSCAT"  IS 'tow by tow total numbers and weights';
  GRANT SELECT ON "GROUNDFISH"."NFGSCAT" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSCAT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSCAT" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSCAT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSCAT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."NFGSCAT" TO "GREYSONP";
