--------------------------------------------------------
--  DDL for Table NFLD_SP_CODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."NFLD_SP_CODES" 
   (	"NFLD_SPEC" VARCHAR2(4 BYTE), 
	"MFD_SPEC" VARCHAR2(4 BYTE), 
	"COMMONNAME" VARCHAR2(24 BYTE), 
	"SCIENTIFICNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."NFLD_SP_CODES" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."NFLD_SP_CODES" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."NFLD_SP_CODES" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."NFLD_SP_CODES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."NFLD_SP_CODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."NFLD_SP_CODES" TO "GREYSONP";
