--------------------------------------------------------
--  DDL for Table NFRAW_INFCAT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."NFRAW_INFCAT" 
   (	"CARD_TYPE" VARCHAR2(1 BYTE), 
	"VESEL" VARCHAR2(2 BYTE), 
	"CRUNO" VARCHAR2(3 BYTE), 
	"SETNO" VARCHAR2(3 BYTE), 
	"SDATE" DATE, 
	"SET_TYPE" VARCHAR2(2 BYTE), 
	"STRAT_LINE" VARCHAR2(3 BYTE), 
	"NAFO" VARCHAR2(2 BYTE), 
	"UNIT_AREA" VARCHAR2(3 BYTE), 
	"LIGHT" VARCHAR2(3 BYTE), 
	"WIND" VARCHAR2(1 BYTE), 
	"FORCE" VARCHAR2(1 BYTE), 
	"SEA" VARCHAR2(1 BYTE), 
	"BOTTOM_TYPE" VARCHAR2(1 BYTE), 
	"MID_TIME" VARCHAR2(4 BYTE), 
	"DUR" VARCHAR2(3 BYTE), 
	"DIST" VARCHAR2(3 BYTE), 
	"RESULT" VARCHAR2(1 BYTE), 
	"DMEAN" VARCHAR2(4 BYTE), 
	"DMIN" VARCHAR2(4 BYTE), 
	"DMAX" VARCHAR2(4 BYTE), 
	"DEPTH_BOT" VARCHAR2(4 BYTE), 
	"SURF_TEMP" VARCHAR2(3 BYTE), 
	"BOT_TEMP" VARCHAR2(3 BYTE), 
	"SLAT" VARCHAR2(5 BYTE), 
	"SLONG" VARCHAR2(5 BYTE), 
	"HOW_POS" VARCHAR2(1 BYTE), 
	"GEAR" VARCHAR2(4 BYTE), 
	"SPEC" VARCHAR2(4 BYTE), 
	"TOTNO" VARCHAR2(6 BYTE), 
	"TOTWGT" VARCHAR2(7 BYTE), 
	"ELAT" VARCHAR2(5 BYTE), 
	"ELONG" VARCHAR2(5 BYTE), 
	"BOTTEMPDEV" VARCHAR2(2 BYTE), 
	"GEARMONDEV" VARCHAR2(2 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
 

   COMMENT ON TABLE "GROUNDFISH"."NFRAW_INFCAT"  IS 'raw data for tow location and catch';
  GRANT SELECT ON "GROUNDFISH"."NFRAW_INFCAT" TO "MFLIB";
 
  GRANT SELECT ON "GROUNDFISH"."NFRAW_INFCAT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."NFRAW_INFCAT" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."NFRAW_INFCAT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."NFRAW_INFCAT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."NFRAW_INFCAT" TO "GREYSONP";
