--------------------------------------------------------
--  DDL for Table OBIS_GS_SPECIES_MANUAL_OLD
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."OBIS_GS_SPECIES_MANUAL_OLD" 
   (	"GIVEN_SPEC_CODE" NUMBER(4,0), 
	"GIVEN_COMMON_NAME" VARCHAR2(38 BYTE), 
	"GIVEN_SCIENT_NAME" VARCHAR2(49 BYTE), 
	"GIVEN_TSN" NUMBER(38,0), 
	"ACCEPTED_TSN" NUMBER, 
	"UNACCEPT_REASON" VARCHAR2(400 BYTE), 
	"FAO_CODE" VARCHAR2(5 BYTE), 
	"FAO_E_COMMON_NAME" VARCHAR2(40 BYTE), 
	"FAO_F_COMMON_NAME" VARCHAR2(40 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."OBIS_GS_SPECIES_MANUAL_OLD" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."OBIS_GS_SPECIES_MANUAL_OLD" TO "GREYSONP";
