--------------------------------------------------------
--  DDL for Table RFREPS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."RFREPS" 
   (	"MISSION" VARCHAR2(15 BYTE), 
	"VESEL" VARCHAR2(10 BYTE), 
	"CRUNO" NUMBER(5,0), 
	"SETNO" VARCHAR2(20 BYTE), 
	"STATION" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 49152 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."RFREPS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."RFREPS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."RFREPS" TO "GREYSONP";
