--------------------------------------------------------
--  DDL for Table SC_TSN_ESRF2
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SC_TSN_ESRF2" 
   (	"ID" NUMBER(10,0), 
	"SPEC_NUM_VDC" VARCHAR2(10 BYTE), 
	"SPEC_NAME_COMMON" VARCHAR2(70 BYTE), 
	"SPEC_NAME_SCIENTIFIC" VARCHAR2(50 BYTE), 
	"TSN" NUMBER(10,0), 
	"TSN_ACCEPTED" NUMBER(10,0), 
	"TSN_USE" NUMBER, 
	"CBIF_HREF" VARCHAR2(102 BYTE), 
	"ITIS_HREF" VARCHAR2(141 BYTE), 
	"FBASE_HREF" VARCHAR2(144 BYTE), 
	"FBASE_HREF_VALID" CHAR(1 BYTE), 
	"LBASE_HREF" VARCHAR2(156 BYTE), 
	"LBASE_HREF_VALID" CHAR(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."SC_TSN_ESRF2" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SC_TSN_ESRF2" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SC_TSN_ESRF2" TO "GREYSONP";
