--------------------------------------------------------
--  DDL for Table SDCFDET_TMP
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDCFDET_TMP" 
   (	"MISSION" VARCHAR2(10 BYTE), 
	"FSHNO" NUMBER(4,0), 
	"FLEN" NUMBER(4,0), 
	"FWT" NUMBER(6,0), 
	"GWT" NUMBER(6,0), 
	"LIVWT" NUMBER(4,0), 
	"GONWT" NUMBER(4,0), 
	"SEX" NUMBER(1,0), 
	"MATURITY" NUMBER(1,0), 
	"GUTCONDITION" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1064960 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."MISSION" IS 'trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."FSHNO" IS 'fish number ';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."FLEN" IS 'fish length';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."FWT" IS 'fish weight ';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."GWT" IS 'gonad weight';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."LIVWT" IS 'liver weight';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."GONWT" IS 'gonad weight';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."SEX" IS 'sex code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."MATURITY" IS 'maturity code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDCFDET_TMP"."GUTCONDITION" IS 'gut condition code ';
 
   COMMENT ON TABLE "GROUNDFISH"."SDCFDET_TMP"  IS 'Stomach Community Samples ';
  GRANT SELECT ON "GROUNDFISH"."SDCFDET_TMP" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDCFDET_TMP" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDCFDET_TMP" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDCFDET_TMP" TO "GREYSONP";
