--------------------------------------------------------
--  DDL for Table SDDET
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDDET" 
   (	"DATASOURCE" VARCHAR2(3 BYTE), 
	"MISSION" VARCHAR2(15 BYTE), 
	"SETNO" NUMBER(3,0), 
	"SAMPLE_INDEX" NUMBER(6,0), 
	"SPEC" NUMBER(4,0), 
	"FSHNO" NUMBER(6,0), 
	"ADATE" DATE, 
	"FWT" NUMBER(7,1), 
	"FLEN" NUMBER(4,0), 
	"TECH" VARCHAR2(10 BYTE), 
	"STOWGT" NUMBER(5,1), 
	"EMPTYWGT" NUMBER(5,1), 
	"FULLNESS" NUMBER(1,0), 
	"STATUS_FLAG" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6348800 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."DATASOURCE" IS 'Trip type code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."MISSION" IS 'Trip Id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."SAMPLE_INDEX" IS 'Unique Stomach identifier';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."SPEC" IS 'Species research code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."FSHNO" IS 'Individual fish number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."ADATE" IS 'Stomach analysis date';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."FWT" IS 'Fish weight in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."FLEN" IS 'Fish fork length in centimetres';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."TECH" IS 'Stomach analysis tech';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."STOWGT" IS 'Total stomach weight incl. contents in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."EMPTYWGT" IS 'Empty stomach weight in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."FULLNESS" IS 'Stomach fullness code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET"."STATUS_FLAG" IS 'row status';
 
   COMMENT ON TABLE "GROUNDFISH"."SDDET"  IS 'Fish analysed';
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "MACDNLDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "SCOTTS";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "GRAVESJ";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT DELETE ON "GROUNDFISH"."SDDET" TO "BMACE";
 
  GRANT INSERT ON "GROUNDFISH"."SDDET" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "BMACE";
 
  GRANT UPDATE ON "GROUNDFISH"."SDDET" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "HARRISLE" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET" TO "GREYSONP";
