--------------------------------------------------------
--  DDL for Table SDDET_EDIT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDDET_EDIT" 
   (	"DATASOURCE" VARCHAR2(3 BYTE), 
	"MISSION" VARCHAR2(15 BYTE), 
	"SETNO" NUMBER(3,0), 
	"SAMPLE_INDEX" NUMBER(6,0), 
	"SPEC" NUMBER(4,0), 
	"FSHNO" NUMBER(6,0), 
	"ADATE" DATE, 
	"FWT" NUMBER(7,1), 
	"FLEN" NUMBER(4,0), 
	"TECH" VARCHAR2(10 BYTE), 
	"STOWGT" NUMBER(5,1), 
	"EMPTYWGT" NUMBER(5,1), 
	"FULLNESS" NUMBER(1,0), 
	"STATUS_FLAG" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 573440 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."DATASOURCE" IS 'Trip type code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."MISSION" IS 'Trip Id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."SAMPLE_INDEX" IS 'Unique Generated Stomach identifier';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."SPEC" IS 'Species research code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."FSHNO" IS 'Individual fish number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."ADATE" IS 'Stomach analysis date';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."FWT" IS 'Fish weight in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."FLEN" IS 'Fish fork length in centimetres';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."TECH" IS 'Stomach analysis tech';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."STOWGT" IS 'Total stomach weight incl. contents in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."EMPTYWGT" IS 'Empty stomach weight in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."FULLNESS" IS 'Stomach fullness code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDET_EDIT"."STATUS_FLAG" IS 'row status';
 
   COMMENT ON TABLE "GROUNDFISH"."SDDET_EDIT"  IS 'Fish analysed';
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "SCOTTS";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT DELETE ON "GROUNDFISH"."SDDET_EDIT" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "HARRISLE" WITH GRANT OPTION;
 
  GRANT UPDATE ON "GROUNDFISH"."SDDET_EDIT" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDDET_EDIT" TO "GREYSONP";
