--------------------------------------------------------
--  DDL for Table SDDIGEST
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDDIGEST" 
   (	"DIGESTION" VARCHAR2(1 BYTE), 
	"DESCRIPTION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDDIGEST"."DIGESTION" IS 'Digestion Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDDIGEST"."DESCRIPTION" IS 'description of Digestion Code';
 
   COMMENT ON TABLE "GROUNDFISH"."SDDIGEST"  IS 'Digestion State Codes ';
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDDIGEST" TO "GREYSONP";
