--------------------------------------------------------
--  DDL for Table SDERRCD
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDERRCD" 
   (	"ERRCODE" NUMBER, 
	"DESCRIPTION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDERRCD"."ERRCODE" IS 'Error Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDERRCD"."DESCRIPTION" IS 'Error description';
 
   COMMENT ON TABLE "GROUNDFISH"."SDERRCD"  IS 'Data error codes ';
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDERRCD" TO "GREYSONP";
