--------------------------------------------------------
--  DDL for Table SDFULLNESS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDFULLNESS" 
   (	"FULLNESS" VARCHAR2(1 BYTE), 
	"DESCRIPTION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDFULLNESS"."FULLNESS" IS 'Stomach Fullness Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDFULLNESS"."DESCRIPTION" IS 'description of Stomach Fullness';
 
   COMMENT ON TABLE "GROUNDFISH"."SDFULLNESS"  IS 'Stomach Fullness Codes ';
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDFULLNESS" TO "GREYSONP";
