--------------------------------------------------------
--  DDL for Table SDHAD_TMP
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDHAD_TMP" 
   (	"SPEC" NUMBER(4,0), 
	"VESEL" VARCHAR2(1 BYTE), 
	"CRUNO" NUMBER(3,0), 
	"STN" NUMBER(3,0), 
	"SETNO" NUMBER(3,0), 
	"FSHNO" NUMBER(4,0), 
	"SDATE" DATE, 
	"STIME" NUMBER(3,0), 
	"SLAT" NUMBER(6,0), 
	"SLONG" NUMBER(6,0), 
	"FLEN" NUMBER(4,0), 
	"FWT" NUMBER(9,2), 
	"FSEX" NUMBER(1,0), 
	"FSTOC" NUMBER(1,0), 
	"LANAL" NUMBER(1,0), 
	"SWT" NUMBER(8,1), 
	"SSPEC" NUMBER(4,0), 
	"SNO" NUMBER(5,0), 
	"SSPECWT" NUMBER(8,1)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2662400 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "GROUNDFISH"."SDHAD_TMP" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDHAD_TMP" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDHAD_TMP" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDHAD_TMP" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDHAD_TMP" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDHAD_TMP" TO "GREYSONP";
