--------------------------------------------------------
--  DDL for Table SDITEM
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDITEM" 
   (	"PREYITEMCD" NUMBER(4,0), 
	"PREYITEM" VARCHAR2(20 BYTE), 
	"PREYSPECIES" VARCHAR2(50 BYTE), 
	"PREYSPECCD" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 32768 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDITEM"."PREYITEMCD" IS 'Food Item Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDITEM"."PREYITEM" IS 'Food Item Group';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDITEM"."PREYSPECIES" IS 'Food Item detail/species';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDITEM"."PREYSPECCD" IS 'Food Item detail/species code';
 
   COMMENT ON TABLE "GROUNDFISH"."SDITEM"  IS 'Prey Item conversion and description ';
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDITEM" TO "GREYSONP";
