--------------------------------------------------------
--  DDL for Table SDMACDET_TMP
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDMACDET_TMP" 
   (	"MISSION" VARCHAR2(10 BYTE), 
	"SETNO" NUMBER(3,0), 
	"FSHNO" NUMBER(4,0), 
	"FLEN" NUMBER(5,1), 
	"FWT" NUMBER(5,1), 
	"SEX" VARCHAR2(1 BYTE), 
	"MATURITY" NUMBER(1,0), 
	"GONADWT" NUMBER(5,2), 
	"AGE" NUMBER(2,0), 
	"REMARKS" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 532480 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."MISSION" IS 'trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."SETNO" IS ' setno';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."FSHNO" IS 'fshno';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."FLEN" IS 'flen';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."FWT" IS 'fwt';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."SEX" IS 'sex';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."MATURITY" IS 'trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."GONADWT" IS 'trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."AGE" IS 'age';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDMACDET_TMP"."REMARKS" IS 'Remarks on age';
 
   COMMENT ON TABLE "GROUNDFISH"."SDMACDET_TMP"  IS 'Mackerel Detail data ';
  GRANT SELECT ON "GROUNDFISH"."SDMACDET_TMP" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDMACDET_TMP" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDMACDET_TMP" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDMACDET_TMP" TO "GREYSONP";
