--------------------------------------------------------
--  DDL for Table SDPRED
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDPRED" 
   (	"SPEC" NUMBER(4,0), 
	"DESCRIPTION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDPRED"."SPEC" IS 'research Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDPRED"."DESCRIPTION" IS 'description/common name';
 
   COMMENT ON TABLE "GROUNDFISH"."SDPRED"  IS 'Predator Species List ';
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "HARRISLE";
 
  GRANT UPDATE ON "GROUNDFISH"."SDPRED" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDPRED" TO "GREYSONP";
