--------------------------------------------------------
--  DDL for Table SDSOURCE
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDSOURCE" 
   (	"DATASOURCE" VARCHAR2(3 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDSOURCE"."DATASOURCE" IS 'Data Source Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSOURCE"."DESCRIPTION" IS 'description of data source';
 
   COMMENT ON TABLE "GROUNDFISH"."SDSOURCE"  IS 'Data Source Descriptions ';
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "HARRISLE";
 
  GRANT UPDATE ON "GROUNDFISH"."SDSOURCE" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDSOURCE" TO "GREYSONP";
