--------------------------------------------------------
--  DDL for Table SDSTO
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDSTO" 
   (	"DATASOURCE" VARCHAR2(3 BYTE), 
	"MISSION" VARCHAR2(15 BYTE), 
	"SETNO" NUMBER(3,0), 
	"SAMPLE_INDEX" NUMBER(6,0), 
	"SPEC" NUMBER(4,0), 
	"FSHNO" NUMBER(6,0), 
	"STO_KEY" ROWID, 
	"PREYITEMCD" NUMBER(4,0), 
	"PREYITEM" VARCHAR2(25 BYTE), 
	"PREYSPECCD" NUMBER(4,0), 
	"PREYSPEC" VARCHAR2(36 BYTE), 
	"PWT" NUMBER(10,4), 
	"PLEN" NUMBER(5,1), 
	"PNUM" NUMBER(6,0), 
	"DIGESTION" VARCHAR2(1 BYTE), 
	"REMARKS" VARCHAR2(150 BYTE), 
	"STATUS_FLAG" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 10608640 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."DATASOURCE" IS 'Data Source';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."MISSION" IS 'Trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."SPEC" IS 'Predator fish species';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."FSHNO" IS 'Individual fish number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."STO_KEY" IS 'generated key to make each stomach item unique';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."PREYITEMCD" IS 'Prey item research code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."PREYITEM" IS 'prey item';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."PREYSPECCD" IS 'Prey species research code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."PREYSPEC" IS 'prey species';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."PWT" IS 'Prey weight in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."PLEN" IS 'Prey length in centimetres';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."PNUM" IS 'number of prey';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."DIGESTION" IS 'digestion state code - use caution for FEP and P70';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."REMARKS" IS 'prey remarks';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO"."STATUS_FLAG" IS 'row status';
 
   COMMENT ON TABLE "GROUNDFISH"."SDSTO"  IS 'Items in stomach contents';
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "MACDNLDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "SCOTTS";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "GRAVESJ";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT DELETE ON "GROUNDFISH"."SDSTO" TO "BMACE";
 
  GRANT INSERT ON "GROUNDFISH"."SDSTO" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "BMACE";
 
  GRANT UPDATE ON "GROUNDFISH"."SDSTO" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "HARRISLE" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "ABUNDY";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO" TO "GREYSONP";
