--------------------------------------------------------
--  DDL for Table SDSTO_EDIT
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDSTO_EDIT" 
   (	"DATASOURCE" VARCHAR2(3 BYTE), 
	"MISSION" VARCHAR2(15 BYTE), 
	"SETNO" NUMBER(3,0), 
	"SAMPLE_INDEX" NUMBER(6,0), 
	"SPEC" NUMBER(4,0), 
	"FSHNO" NUMBER(6,0), 
	"STO_KEY" ROWID, 
	"PREYITEMCD" NUMBER(4,0), 
	"PREYITEM" VARCHAR2(25 BYTE), 
	"PREYSPECCD" NUMBER(4,0), 
	"PREYSPEC" VARCHAR2(36 BYTE), 
	"PWT" NUMBER(10,4), 
	"PLEN" NUMBER(5,1), 
	"PNUM" NUMBER(6,0), 
	"DIGESTION" VARCHAR2(1 BYTE), 
	"REMARKS" VARCHAR2(150 BYTE), 
	"STATUS_FLAG" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1146880 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."DATASOURCE" IS 'Data Source';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."MISSION" IS 'Trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."SETNO" IS 'Set Number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."SAMPLE_INDEX" IS 'Unique Generated Stomach identifier';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."SPEC" IS 'Predator fish species';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."FSHNO" IS 'Individual fish number';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."STO_KEY" IS 'generated key to make each stomach item unique';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."PREYITEMCD" IS 'Prey item research code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."PREYITEM" IS 'prey item';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."PREYSPECCD" IS 'Prey species research code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."PREYSPEC" IS 'prey species';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."PWT" IS 'Prey weight in grams';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."PLEN" IS 'Prey length in centimetres';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."PNUM" IS 'number of prey';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."DIGESTION" IS 'digestion state code - use caution for FEP and P70';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."REMARKS" IS 'prey remarks';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDSTO_EDIT"."STATUS_FLAG" IS 'row status';
 
   COMMENT ON TABLE "GROUNDFISH"."SDSTO_EDIT"  IS 'Items in stomach contents';
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "SCOTTS";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT DELETE ON "GROUNDFISH"."SDSTO_EDIT" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "HARRISLE" WITH GRANT OPTION;
 
  GRANT UPDATE ON "GROUNDFISH"."SDSTO_EDIT" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDSTO_EDIT" TO "GREYSONP";
