--------------------------------------------------------
--  DDL for Table SDTEMP
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDTEMP" 
   (	"SAMPSEQ" NUMBER, 
	"TRIP" VARCHAR2(15 BYTE), 
	"SETNO" NUMBER, 
	"TRIP_DATE" DATE, 
	"SPEC" VARCHAR2(30 BYTE), 
	"FSHNO" NUMBER(4,0), 
	"ANAL_DATE" DATE, 
	"TECH" VARCHAR2(15 BYTE), 
	"TOTAL_WT" NUMBER(8,3), 
	"EMPTY_WT" NUMBER(8,3), 
	"FULLNESS" NUMBER(4,0), 
	"INDEX1" NUMBER(6,0), 
	"CONDITION" NUMBER(1,0), 
	"FISHLEN" NUMBER(6,0), 
	"INDEX2" NUMBER(6,0), 
	"ITEM" VARCHAR2(20 BYTE), 
	"SPNAME" VARCHAR2(25 BYTE), 
	"LENGTH" NUMBER(8,3), 
	"WEIGHT" NUMBER(8,3), 
	"NUM" NUMBER(6,0), 
	"REMARKS" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4259840 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "GROUNDFISH"."SDTEMP" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDTEMP" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDTEMP" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDTEMP" TO "GREYSONP";
