--------------------------------------------------------
--  DDL for Table SDTECH
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDTECH" 
   (	"TECHCODE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDTECH"."TECHCODE" IS 'Technician Code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDTECH"."DESCRIPTION" IS 'Technician Name(s)';
 
   COMMENT ON TABLE "GROUNDFISH"."SDTECH"  IS 'Technician codes and Names ';
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "HARRISLE";
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDTECH" TO "GREYSONP";
