--------------------------------------------------------
--  DDL for Table SDTRIPS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDTRIPS" 
   (	"DATASOURCE" VARCHAR2(3 BYTE), 
	"MISSION" VARCHAR2(15 BYTE), 
	"TRIPSTATUS" VARCHAR2(10 BYTE), 
	"EDITID" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 163840 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDTRIPS"."DATASOURCE" IS 'Trip type code';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDTRIPS"."MISSION" IS 'Trip Id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDTRIPS"."TRIPSTATUS" IS 'Trip Status';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDTRIPS"."EDITID" IS 'User Id for lastEdit';
 
   COMMENT ON TABLE "GROUNDFISH"."SDTRIPS"  IS 'Stomach database trip status details ';
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT DELETE ON "GROUNDFISH"."SDTRIPS" TO "BMACE";
 
  GRANT INSERT ON "GROUNDFISH"."SDTRIPS" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "BMACE";
 
  GRANT UPDATE ON "GROUNDFISH"."SDTRIPS" TO "BMACE";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "HARRISLE" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "MACDONALDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDTRIPS" TO "GREYSONP";
