--------------------------------------------------------
--  DDL for Table SDUSER
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDUSER" 
   (	"USERNAME" VARCHAR2(10 BYTE), 
	"USERPASSWORD" VARCHAR2(10 BYTE), 
	"PERMISSIONS" VARCHAR2(5 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDUSER"."USERNAME" IS 'User Name';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDUSER"."USERPASSWORD" IS 'userPassword';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDUSER"."PERMISSIONS" IS 'permissions';
 
   COMMENT ON TABLE "GROUNDFISH"."SDUSER"  IS 'Stomach Database System Users';
  GRANT SELECT ON "GROUNDFISH"."SDUSER" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SDUSER" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SDUSER" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SDUSER" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDUSER" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDUSER" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDUSER" TO "GREYSONP";
