--------------------------------------------------------
--  DDL for Table SDWHLFISHDET_TMP
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SDWHLFISHDET_TMP" 
   (	"FSHNO" NUMBER(4,0), 
	"SDATE" DATE, 
	"TRIPID" VARCHAR2(10 BYTE), 
	"SETNO" NUMBER(4,0), 
	"FLEN" NUMBER(4,0), 
	"FWT" NUMBER(4,0), 
	"STOCONT" VARCHAR2(1 BYTE), 
	"SPEC" NUMBER(4,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 16384 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
 

   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."FSHNO" IS 'trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."SDATE" IS 'set date';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."TRIPID" IS 'trip id';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."SETNO" IS 'set no';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."FLEN" IS 'fish len';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."FWT" IS 'fish wt';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."STOCONT" IS 'stomach has contents';
 
   COMMENT ON COLUMN "GROUNDFISH"."SDWHLFISHDET_TMP"."SPEC" IS 'species';
 
   COMMENT ON TABLE "GROUNDFISH"."SDWHLFISHDET_TMP"  IS 'Whole Fish.xls  ';
  GRANT SELECT ON "GROUNDFISH"."SDWHLFISHDET_TMP" TO "MFD_STOMACH";
 
  GRANT SELECT ON "GROUNDFISH"."SDWHLFISHDET_TMP" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SDWHLFISHDET_TMP" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SDWHLFISHDET_TMP" TO "GREYSONP";
