--------------------------------------------------------
--  DDL for Table SETRPTTABLE
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SETRPTTABLE" 
   (	"VESSEL" CHAR(1 BYTE), 
	"CRUISE_NUMBER" NUMBER(2,0), 
	"SET_NUMBER" NUMBER(2,0), 
	"SET_ORDER" VARCHAR2(2 BYTE), 
	"SP_CODE" VARCHAR2(4 BYTE), 
	"SPECIES_NAME" VARCHAR2(38 BYTE), 
	"GROUPING" NUMBER(1,0), 
	"SEX" NUMBER(1,0), 
	"FISH_CAUGHT" NUMBER, 
	"NO_BSKTS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 24576 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."SETRPTTABLE" TO "MFLIB" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."SETRPTTABLE" TO "VDC";
 
  GRANT SELECT ON "GROUNDFISH"."SETRPTTABLE" TO "VDC_DEV";
 
  GRANT SELECT ON "GROUNDFISH"."SETRPTTABLE" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SETRPTTABLE" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SETRPTTABLE" TO "GREYSONP";
