--------------------------------------------------------
--  DDL for Table SPECIESCODESFR
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SPECIESCODESFR" 
   (	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"SPECIESCODE" NUMBER(5,0), 
	"ENGLISHCOMMONNAME" VARCHAR2(50 BYTE), 
	"FRENCHCOMMONNAME" VARCHAR2(50 BYTE), 
	"SCIENTIFICNAME" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."SPECIESCODESFR" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SPECIESCODESFR" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SPECIESCODESFR" TO "GREYSONP";
