--------------------------------------------------------
--  DDL for Table SPECIESORDER
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."SPECIESORDER" 
   (	"SPECIES_NO" VARCHAR2(4 BYTE), 
	"SET_ORDER" VARCHAR2(2 BYTE), 
	"SPECIES_NAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."SPECIESORDER" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."SPECIESORDER" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."SPECIESORDER" TO "GREYSONP";
