--------------------------------------------------------
--  DDL for Table TEMP_MULTI_SPCODES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."TEMP_MULTI_SPCODES" 
   (	"RESEARCH" NUMBER(4,0), 
	"FAO" VARCHAR2(3 BYTE), 
	"A3_CODE" VARCHAR2(255 BYTE), 
	"SCIENTIF" VARCHAR2(49 BYTE), 
	"SCIENTIFIC_NAME" VARCHAR2(255 BYTE), 
	"IML_SCIENTIFICNAME" VARCHAR2(50 BYTE), 
	"FAO_ENGLISH_NAME" VARCHAR2(255 BYTE), 
	"IML_ENGLISHCOMMONNAME" VARCHAR2(50 BYTE), 
	"COMMON" VARCHAR2(38 BYTE), 
	"FAO_FRENCH_NAME" VARCHAR2(255 BYTE), 
	"IML_FRENCHCOMMONNAME" VARCHAR2(50 BYTE), 
	"FAO_SPANISH_NAME" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."TEMP_MULTI_SPCODES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."TEMP_MULTI_SPCODES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."TEMP_MULTI_SPCODES" TO "GREYSONP";
