--------------------------------------------------------
--  DDL for Table TGSSTRATUM
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."TGSSTRATUM" 
   (	"STRAT" VARCHAR2(5 BYTE), 
	"LABS" VARCHAR2(30 BYTE), 
	"DMIN_M" NUMBER(5,0), 
	"DMAX_M" NUMBER(5,0), 
	"DMIN_I" NUMBER(4,0), 
	"DMAX_I" NUMBER(4,0), 
	"AREA_M" NUMBER(5,0), 
	"AREA_I" NUMBER(4,0), 
	"DEPTH_M" NUMBER(4,0), 
	"DEPTH_I" NUMBER(3,0), 
	"NAME" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."TGSSTRATUM" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."TGSSTRATUM" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."TGSSTRATUM" TO "GREYSONP";
