--------------------------------------------------------
--  DDL for Table USGMBIS_STATION
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."USGMBIS_STATION" 
   (	"Station Number" NUMBER, 
	"Voyage Number" NUMBER, 
	"Voyage Name" VARCHAR2(10 BYTE), 
	"Station Name" VARCHAR2(16 BYTE), 
	"Station Type" NUMBER, 
	"Stratum" VARCHAR2(5 BYTE), 
	"Station Latitude" VARCHAR2(17 BYTE), 
	"Station Longitude" VARCHAR2(17 BYTE), 
	"Station Date" DATE, 
	"Station Depth" NUMBER, 
	"Tow Distance" NUMBER(6,2)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 860160 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_STATION" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_STATION" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_STATION" TO "GREYSONP";
