--------------------------------------------------------
--  DDL for Table USGMBIS_SPECIES
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."USGMBIS_SPECIES" 
   (	"Species Number" NUMBER(4,0), 
	"NMFS" NUMBER, 
	"FAO" VARCHAR2(3 BYTE), 
	"Common Species Name" VARCHAR2(38 BYTE), 
	"Scientific Species Name" VARCHAR2(49 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_SPECIES" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_SPECIES" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_SPECIES" TO "GREYSONP";
