--------------------------------------------------------
--  DDL for Table USGMBIS_VOYAGE
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."USGMBIS_VOYAGE" 
   (	"Voyage Number" NUMBER, 
	"Voyage Name" VARCHAR2(10 BYTE), 
	"Voyage Description" VARCHAR2(9 BYTE), 
	"Voyage Start Date" DATE, 
	"Voyage End Date" DATE, 
	"Ship Name" VARCHAR2(3 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 286720 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_VOYAGE" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_VOYAGE" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."USGMBIS_VOYAGE" TO "GREYSONP";
