--------------------------------------------------------
--  DDL for Table USGSINF
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."USGSINF" 
   (	"ID" VARCHAR2(18 BYTE), 
	"MISSION" VARCHAR2(10 BYTE), 
	"CRUISE" NUMBER(8,0), 
	"STRATUM" VARCHAR2(5 BYTE), 
	"TOW" VARCHAR2(3 BYTE), 
	"STATION" VARCHAR2(4 BYTE), 
	"SDATE" DATE, 
	"TIME" VARCHAR2(8 BYTE), 
	"SLAT" NUMBER(8,2), 
	"SLONG" NUMBER(8,2), 
	"ELAT" NUMBER(8,2), 
	"ELONG" NUMBER(8,2), 
	"AREA" VARCHAR2(3 BYTE), 
	"DUR" NUMBER(3,0), 
	"DIST" NUMBER(6,2), 
	"HOWD" NUMBER(1,0), 
	"SPEED" NUMBER(6,2), 
	"HOWS" NUMBER(1,0), 
	"DMIN" NUMBER(4,0), 
	"DMAX" NUMBER(4,0), 
	"WIND" NUMBER(3,0), 
	"FORCE" NUMBER(2,0), 
	"CURNT" NUMBER(1,0), 
	"TYPE" NUMBER(1,0), 
	"GEAR" VARCHAR2(2 BYTE), 
	"AUX" VARCHAR2(4 BYTE), 
	"DEPTH" NUMBER(4,0), 
	"ETIME" DATE, 
	"START_DEPTH" NUMBER, 
	"END_DEPTH" NUMBER, 
	"SURFACE_TEMPERATURE" NUMBER, 
	"BOTTOM_TEMPERATURE" NUMBER, 
	"BOTTOM_SALINITY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "GROUNDFISH"."USGSINF" TO "NWAGSCOL" WITH GRANT OPTION;
 
  GRANT SELECT ON "GROUNDFISH"."USGSINF" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."USGSINF" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."USGSINF" TO "GREYSONP";
