--------------------------------------------------------
--  DDL for Table USGSINF_INVALID
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."USGSINF_INVALID" 
   (	"ID" VARCHAR2(18 BYTE), 
	"MISSION" VARCHAR2(10 BYTE), 
	"CRUISE" VARCHAR2(6 BYTE), 
	"STRATUM" VARCHAR2(5 BYTE), 
	"TOW" VARCHAR2(3 BYTE), 
	"STATION" VARCHAR2(4 BYTE), 
	"SDATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "GROUNDFISH"."USGSINF_INVALID" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."USGSINF_INVALID" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."USGSINF_INVALID" TO "GREYSONP";
