--------------------------------------------------------
--  DDL for Table USGSDET
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."USGSDET" 
   (	"CRUISE" VARCHAR2(4 BYTE), 
	"STRATUM" VARCHAR2(5 BYTE), 
	"TOW" VARCHAR2(3 BYTE), 
	"STATION" VARCHAR2(4 BYTE), 
	"SVSPP" VARCHAR2(3 BYTE), 
	"INDID" NUMBER(3,0), 
	"LENGTH" NUMBER(5,2), 
	"SEX" VARCHAR2(1 BYTE), 
	"INDWT" NUMBER, 
	"AGE" NUMBER(2,0), 
	"MATURITY" VARCHAR2(1 BYTE), 
	"CSTSID" VARCHAR2(16 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 2867200 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH"  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "GROUNDFISH"."USGSDET" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."USGSDET" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."USGSDET" TO "GREYSONP";
