--------------------------------------------------------
--  DDL for Table USS_MASTER_CRUISE_DETAILS
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."USS_MASTER_CRUISE_DETAILS" 
   (	"SVVESSEL" VARCHAR2(2 BYTE), 
	"VESSEL_NUM" VARCHAR2(5 BYTE), 
	"YEAR" VARCHAR2(4 BYTE), 
	"PURPOSE_CODE" VARCHAR2(2 BYTE), 
	"STATUS_CODE" VARCHAR2(2 BYTE), 
	"CRUISE6" VARCHAR2(6 BYTE), 
	"CRUISE" VARCHAR2(6 BYTE), 
	"CRUISE_OLD" VARCHAR2(6 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."USS_MASTER_CRUISE_DETAILS" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."USS_MASTER_CRUISE_DETAILS" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."USS_MASTER_CRUISE_DETAILS" TO "GREYSONP";
