--------------------------------------------------------
--  DDL for Table WSSECOPATHCODE
--------------------------------------------------------

  CREATE TABLE "GROUNDFISH"."WSSECOPATHCODE" 
   (	"SPEC" NUMBER(4,0), 
	"MINLEN" NUMBER(6,1), 
	"MAXLEN" NUMBER(6,1), 
	"ECOCODE" NUMBER(3,0), 
	"COMM" VARCHAR2(38 BYTE), 
	"SPECIES" VARCHAR2(49 BYTE), 
	"ECOGROUP" VARCHAR2(15 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "MFD_GROUNDFISH" ;
  GRANT SELECT ON "GROUNDFISH"."WSSECOPATHCODE" TO "NWAGS";
 
  GRANT SELECT ON "GROUNDFISH"."WSSECOPATHCODE" TO "RICARDD";
 
  GRANT SELECT ON "GROUNDFISH"."WSSECOPATHCODE" TO "HUBLEYB";
 
  GRANT SELECT ON "GROUNDFISH"."WSSECOPATHCODE" TO "GREYSONP";
