

  lookup.numbers.vars = function() {
    # vars in ("name", "filter") pairs:
    vars=  c(
      "totno.male",             "male",
      "totno.male.com",         "m.com",
      "totno.male.ncom",        "m.ncom",
      "totno.female",           "female",
      "totno.female.berried",   "f.berried",
      "totno.female.primiparous","primiparous",
      "totno.female.multiparous", "multiparous",
      "totno.female.mat",       "f.mat",
      "totno.female.imm",       "f.imm",
      "totno.male.mat",         "m.mat",
      "totno.male.imm",         "m.imm",
      "totno.male.soft",      "m.soft",
      "totno.male.hard",      "m.hard",
      "totno.female.soft",      "f.soft",
      "totno.female.hard",      "f.hard",
      "totno.male.com.CC1to2",      "m.CC1to2",
      "totno.male.com.CC3to4",      "m.CC3to4",
      "totno.male.com.CC1",         "m.CC1",
      "totno.male.com.CC2",         "m.CC2",
      "totno.male.com.CC3",         "m.CC3",
      "totno.male.com.CC4",         "m.CC4",
      "totno.male.com.CC5",         "m.CC5",
      "totno.female.CC1to2",      "f.CC1to2",
      "totno.female.CC3to4",      "f.CC3to4",
      "totno.female.CC3",      "f.CC3",
      "totno.female.CC4",      "f.CC4",
      "totno.female.CC5",         "f.CC5",
      "f7.no",  "f7",
      "f8.no",  "f8",
      "f9.no",  "f9",
      "f10.no",  "f10",
      "m7.no",  "m7",
      "m8.no",  "m8",
      "m9.no",  "m9",
      "m10.no",  "m10",
      "mi123.no",                  "mi123",
      "mi4.no",                    "mi4",
      "mi5.no",                    "mi5",
      "mi6.no",                    "mi6",
      "mi7.no",                    "mi7",
      "mi8.no",                    "mi8",
      "mi9.no",                    "mi9",
      "mi10.no",                   "mi10",
      "mi11.no",                   "mi11",
      "mi12.no",                   "mi12",
      "mi9.skip.moulter.no",  "mi9.skip.moulter",
      "mi10.skip.moulter.no",  "mi10.skip.moulter",
      "mi11.skip.moulter.no",  "mi11.skip.moulter",
      "mi12.skip.moulter.no",  "mi12.skip.moulter",
      "ma9.no",                    "ma9",
      "ma10.no",                   "ma10",
      "ma11.no",                   "ma11",
      "ma12.no",                   "ma12",
      "ma13.no",                   "ma13",
      "ma9.CC1to2.no",  "ma9.CC1to2",
      "ma10.CC1to2.no", "ma10.CC1to2",
      "ma11.CC1to2.no", "ma11.CC1to2",
      "ma12.CC1to2.no", "ma12.CC1to2",
      "ma13.CC1to2.no", "ma13.CC1to2",
      "ma9.CC3to4.no",  "ma9.CC3to4",
      "ma10.CC3to4.no", "ma10.CC3to4",
      "ma11.CC3to4.no", "ma11.CC3to4",
      "ma12.CC3to4.no", "ma12.CC3to4",
      "ma13.CC3to4.no", "ma13.CC3to4",
      "ma9.CC5.no",  "ma9.CC5",
      "ma10.CC5.no", "ma10.CC5",
      "ma11.CC5.no", "ma11.CC5",
      "ma12.CC5.no", "ma12.CC5",
      "ma13.CC5.no", "ma13.CC5",
      "fi1234.no",                 "fi1234",
      "fi5.no",                    "fi5",
      "fi6.no",                    "fi6",
      "fi7.no",                    "fi7",
      "fi8.no",                    "fi8",
      "fi9.no",                    "fi9",
      "fi10.no",                   "fi10",
      "fi6.adolescent.no",      "fi6.adolescent",
      "fi7.adolescent.no",      "fi7.adolescent",
      "fi8.adolescent.no",      "fi8.adolescent",
      "fi9.adolescent.no",      "fi9.adolescent",
      "fi10.adolescent.no",      "fi10.adolescent",
      "fi6.preprimiparous.no",  "fi6.preprimiparous",
      "fi7.preprimiparous.no",  "fi7.preprimiparous",
      "fi8.preprimiparous.no",  "fi8.preprimiparous",
      "fi9.preprimiparous.no",  "fi9.preprimiparous",
      "fi10.preprimiparous.no",  "fi10.preprimiparous",
      "fa7.no",  "fa7",
      "fa8.no",  "fa8",
      "fa9.no",  "fa9",
      "fa10.no",  "fa10",
      "fa7.berried.no",  "fa7.berried",
      "fa8.berried.no",  "fa8.berried",
      "fa9.berried.no",  "fa9.berried",
      "fa10.berried.no",  "fa10.berried",
      "fa7.primiparous.no",  "fa7.primiparous",
      "fa8.primiparous.no",  "fa8.primiparous",
      "fa9.primiparous.no",  "fa9.primiparous",
      "fa10.primiparous.no",  "fa10.primiparous",
      "fa7.multiparous.no",  "fa7.multiparous",
      "fa8.multiparous.no",  "fa8.multiparous",
      "fa9.multiparous.no",  "fa9.multiparous",
      "fa10.multiparous.no",  "fa10.multiparous",
      "fa7.senile.no",  "fa7.senile",
      "fa8.senile.no",  "fa8.senile",
      "fa9.senile.no",  "fa9.senile",
      "fa10.senile.no",  "fa10.senile",
      "R0a.no",                  "R0all",
      "R1a.no",                  "R1all",
      "R0.no",                  "R0",
      "R1.no",                  "R1",
      "R2.no",                  "R2",
      "R3.no",                  "R3",
      "R4.no",                  "R4",
      "R5p.no",                 "R5p",
           "male.small.no",          "male.small",
            "male.large.no",          "male.large",
            "female.small.no",          "female.small",
            "female.large.no",          "female.large",
        "dwarf.no",               "m.dwarf",
      "pre.recruit.no",         "pre.recruit",
      "totno.male.skip.moulter",        "skip.moulter"
    )
    vars = matrix( vars, ncol=2, byrow=T)

    return (vars )

  }


