groundfish.track.selector<-function() {
  library(RODBC)
  channel <-  odbcConnect("PTRAN",uid = oracle.personal.username,pwd = oracle.personal.password)
  # query="SELECT DISTINCT
  # GROUNDFISH.GSMISSIONS.MISSION,
  # GROUNDFISH.GSINF.SETNO,
  # (SUBSTR(GROUNDFISH.GSINF.SLONG,1,2)+ROUND(((GROUNDFISH.GSINF.SLONG-(SUBSTR(GROUNDFISH.GSINF.SLONG,1,2)*100))/60),2))*-1 SLONG,
  # (SUBSTR(GROUNDFISH.GSINF.SLAT,1,2)+ROUND(((GROUNDFISH.GSINF.SLAT-(SUBSTR(GROUNDFISH.GSINF.SLAT,1,2)*100))/60),2)) SLAT,
  # (SUBSTR(GROUNDFISH.GSINF.ELONG,1,2)+ROUND(((GROUNDFISH.GSINF.ELONG-(SUBSTR(GROUNDFISH.GSINF.ELONG,1,2)*100))/60),2))*-1 ELONG,
  # (SUBSTR(GROUNDFISH.GSINF.ELAT,1,2)+ROUND(((GROUNDFISH.GSINF.ELAT-(SUBSTR(GROUNDFISH.GSINF.ELAT,1,2)*100))/60),2)) ELAT,
  # GROUNDFISH.GSINF.SDATE,
  # to_char(GROUNDFISH.GSINF.SDATE,'YYYY') YEAR
  # FROM GROUNDFISH.GSMISSIONS
  # INNER JOIN GROUNDFISH.GSINF
  # ON GROUNDFISH.GSMISSIONS.MISSION =GROUNDFISH.GSINF.MISSION
  # WHERE to_char(GROUNDFISH.GSINF.SDATE,'YYYY')>='2010'
  # AND GROUNDFISH.GSINF.TYPE =1
  # "
  query="SELECT GROUNDFISH.GSINF.MISSION,
  GROUNDFISH.GSINF.SETNO,
  to_char(GROUNDFISH.GSINF.SDATE,'YYYY') YEAR,
  GROUNDFISH.GSINF.SDATE,
  (SUBSTR(GROUNDFISH.GSINF.SLONG,1,2)+ROUND(((GROUNDFISH.GSINF.SLONG-(SUBSTR(GROUNDFISH.GSINF.SLONG,1,2)*100))/60),2))*-1 SLONG,
  (SUBSTR(GROUNDFISH.GSINF.SLAT,1,2)+ROUND(((GROUNDFISH.GSINF.SLAT-(SUBSTR(GROUNDFISH.GSINF.SLAT,1,2)*100))/60),2)) SLAT,
  (SUBSTR(GROUNDFISH.GSINF.ELONG,1,2)+ROUND(((GROUNDFISH.GSINF.ELONG-(SUBSTR(GROUNDFISH.GSINF.ELONG,1,2)*100))/60),2))*-1 ELONG,
  (SUBSTR(GROUNDFISH.GSINF.ELAT,1,2)+ROUND(((GROUNDFISH.GSINF.ELAT-(SUBSTR(GROUNDFISH.GSINF.ELAT,1,2)*100))/60),2)) ELAT,
  GROUNDFISH.GSCAT.TOTNO,
  GROUNDFISH.GSCAT.TOTWGT
  FROM GROUNDFISH.GSINF
  INNER JOIN GROUNDFISH.GSCAT
  ON GROUNDFISH.GSINF.MISSION = GROUNDFISH.GSCAT.MISSION
  AND GROUNDFISH.GSINF.SETNO  = GROUNDFISH.GSCAT.SETNO
  WHERE GROUNDFISH.GSINF.TYPE = 1
  AND GROUNDFISH.GSCAT.SPEC   = 6611
  AND to_char(GROUNDFISH.GSINF.SDATE,'YYYY') >= 2015"
  data <- sqlQuery(channel,query)
  browser()
  #want to add the null sets
# query.nullsets="SELECT GROUNDFISH.GSINF.MISSION,
#   GROUNDFISH.GSINF.SETNO,
#   to_char(GROUNDFISH.GSINF.SDATE,'YYYY') YEAR,
#   GROUNDFISH.GSINF.SDATE,
#   (SUBSTR(GROUNDFISH.GSINF.SLONG,1,2)+ROUND(((GROUNDFISH.GSINF.SLONG-(SUBSTR(GROUNDFISH.GSINF.SLONG,1,2)*100))/60),2))*-1 SLONG,
#   (SUBSTR(GROUNDFISH.GSINF.SLAT,1,2)+ROUND(((GROUNDFISH.GSINF.SLAT-(SUBSTR(GROUNDFISH.GSINF.SLAT,1,2)*100))/60),2)) SLAT,
#   (SUBSTR(GROUNDFISH.GSINF.ELONG,1,2)+ROUND(((GROUNDFISH.GSINF.ELONG-(SUBSTR(GROUNDFISH.GSINF.ELONG,1,2)*100))/60),2))*-1 ELONG,
#   (SUBSTR(GROUNDFISH.GSINF.ELAT,1,2)+ROUND(((GROUNDFISH.GSINF.ELAT-(SUBSTR(GROUNDFISH.GSINF.ELAT,1,2)*100))/60),2)) ELAT,
#   0 TOTNO,
#   0 TOTWGT
#   FROM GROUNDFISH.GSINF
#   INNER JOIN GROUNDFISH.GSCAT
#   ON GROUNDFISH.GSINF.MISSION = GROUNDFISH.GSCAT.MISSION
#   AND GROUNDFISH.GSINF.SETNO  = GROUNDFISH.GSCAT.SETNO
#   WHERE GROUNDFISH.GSINF.TYPE = 1
#   AND to_char(GROUNDFISH.GSINF.SDATE,'YYYY') >= 2015"
# data.nullsets <- sqlQuery(channel,query.nullsets)
# all=rbind(data,data.nullsets)
# all$check<-duplicated(all)
  #arrange coordinates appropriate for plot.kml.r
  # 1) pull out coordinates, append order field
  slats=data[,c("MISSION","SETNO","SLAT","SLONG")]
  names(slats) = c("MISSION","SETNO", "LAT","LONG")
  slats$ORD=1
  elats=data[,c("MISSION","SETNO","ELAT","ELONG")]
  names(elats) = c("MISSION","SETNO", "LAT","LONG")
  elats$ORD=2
  # 2) remove coordinates
  data=subset(data, select=-c(SLAT,SLONG,ELAT,ELONG))
  data.s=merge(data,slats)
  data.e=merge(data,elats)
  data=rbind(data.s,data.e)
#   data$LAT=na.zero(data$LAT)
#   data$LONG=na.zero(data$LONG)
  rm(data.s)
  rm(data.e)
  #remove NAs (convert to 0)
  data[which(is.na(data$LAT)),c("LAT")]<-0
  data[which(is.na(data$LONG)),c("LONG")]<-0
  
  results = list(data, query)
}
#plot.kml(data1, metadata=c("crap1"), pid=c("MISSION","SETNO"), ord="ORD", labelFields=c("SETNO"),folderFields=c("YEAR","MISSION"),colourField="MISSION", filename="groundfish1", drawPolys=F)